# Writes assets/img/LICENCES.md: every photo used on the site, with its author, licence and source,
# read from the photo figures in sections/*.html. Re-run after adding or removing a photo.
import os, re, glob, html
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/'
rows = []
for f in sorted(glob.glob(ROOT + 'sections/*.html')):
    for fig in re.findall(r'<figure class="photo">.*?</figure>', open(f).read(), re.S):
        src = re.search(r'src="assets/img/([^"]+)"', fig).group(1)
        credit = re.search(r'<span class="credit">Photo: (.*?)</span>', fig, re.S).group(1)
        parts = [html.unescape(re.sub(r'<[^>]+>', '', x)).strip() for x in credit.split(', ')]
        lic_url = re.findall(r'href="([^"]+)"', credit)
        source = lic_url[-1]
        lic = parts[-2] if len(parts) >= 3 else ''
        author = ', '.join(parts[:-2])
        rows.append((src, os.path.basename(f), author, lic, source))
out = ['# Image credits', '',
       'Generated by `tools/gen_image_credits.py` from the photo figures in `sections/`. Do not edit by hand.', '',
       'Every image here is a copy of a file on Wikimedia Commons, used under the licence shown. Follow the source link for the original, its full description and the licence terms.', '',
       '| File | Used in | Author | Licence | Source |', '|---|---|---|---|---|']
out += [f'| `{s}` | `{sec}` | {a} | {l} | <{u}> |' for s, sec, a, l, u in rows]
open(ROOT + 'assets/img/LICENCES.md', 'w').write('\n'.join(out) + '\n')
print(len(rows), 'images')
