# Generates sections/05-deck.html for Sailing 101.
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_common import *
import gen_deck_diagrams as g

page = f'''<section id="deck">
  <h2>Deck hardware and steering</h2>
  <p class="lead">Everything bolted through the deck is a way in for water; everything between the wheel and the rudder is a way to lose control of the boat. This section covers both: how the boat is steered and what fails, how the anchor gear works, what the winches, cleats and guardrails do, and how to keep a forty-year-old deck dry. In a hurry? <a href="#deck--checklist">Jump to the deck check</a>.</p>

  <div class="first-words">
    <p>Seven words before anything else</p>
    <dl>
      <dt>Helm</dt><dd>The wheel or tiller you steer with, and the place you stand to do it.</dd>
      <dt>Stock and quadrant</dt><dd>The stock is the shaft the rudder turns on. The quadrant is the fan-shaped fitting clamped to its top that wheel steering pulls on.</dd>
      <dt>Pedestal</dt><dd>The column in the cockpit that the wheel is mounted on. The compass usually sits on top of it.</dd>
      <dt>Ground tackle</dt><dd>Everything you anchor with: the anchor, the chain or rope (the rode), and the fittings they run through.</dd>
      <dt>Windlass and gypsy</dt><dd>The windlass is a winch for anchor chain. The gypsy is its notched wheel, shaped to grip one exact size of chain.</dd>
      <dt>Bedding</dt><dd>The sealant under a fitting that keeps water out of the deck. When it fails, the deck core rots.</dd>
      <dt>Backing plate</dt><dd>A metal or plywood plate under the deck that spreads a fitting’s load, so the bolts cannot pull through.</dd>
    </dl>
    <p class="first-words__note">Tack, gybe, head to wind and the other sailing verbs are explained in the <a href="#rig--sailing-words">six-word box at the top of Rig and sails</a>. Two more used here: a <strong>reach</strong> is sailing with the wind from the side (a <strong>broad reach</strong> has it slightly behind the side), and <strong>Force 4</strong> or <strong>Force 7</strong> are wind strengths on the Beaufort scale, about 11 to 16 knots and 28 to 33 knots.</p>
  </div>
  <p class="conf-key"><b>Marks used below:</b> {ONE} means the fact comes from a single source; {TWO} means sources disagree or the figure is anecdotal (a forum, a broker’s listing of one boat, or an owner report); {TBC} means not yet verified. Everything unmarked is supported by at least two sources listed under “Sources and confidence” at the end of each topic.</p>

  <h3>Tiller or wheel</h3>
  <p>A tiller is a lever bolted straight to the top of the rudder stock; a wheel turns the rudder through a mechanism. Two boats in the reference fleet steer with a tiller (the Sadler 32, and the Gib’Sea 31 {TWO}), three with a wheel (the Moody 33, the Bavaria 1060 {TWO} and the Gib’Sea 33), and the Finnsailer 35 has two wheels, in the cockpit and in the wheelhouse, joined by hydraulics {TWO}. Four ways of joining a wheel to a rudder are drawn below; the cable-and-chain system, the common one, is then shown in detail.</p>

{figure('fig-steering-types', 'steering types', '0 0 900 300', 'Four ways to steer: tiller, cable and chain, rod, hydraulic', 'Four panels, bow to the right, each showing the rudder stock rising through the stern of the boat. A tiller lever on the stock head with an extension; a pedestal wheel driving a chain and wires over sheaves to a quadrant on the stock; a pedestal with a gearbox at each end of a solid rod; and a wheel driving a hydraulic pump with two hoses to a ram that pushes a tiller arm on the stock.', g.steering_types(), 'Bow to the right; the hull is shown cut through. A tiller is the whole system in one part. Every wheel system adds parts between your hand and the rudder, and each part is something to inspect.', note=HINT)}

{compare('Steering systems at a glance', ['', 'Tiller', 'Cable and chain', 'Rod (mechanical)', 'Hydraulic'], [
  ['Feel', 'direct, every wave', 'good; goes dead if the cables are over-tight', 'precise, slightly heavy', 'none: the wheel does not tell you what the rudder is doing'],
  ['Parts to fail', 'none', 'chain, two wires, sheaves, quadrant, stops', 'two gearboxes, a rod, rod ends', 'pump, hoses, ram, seals, fluid'],
  ['If it fails', 'it is the emergency tiller', 'emergency tiller on the stock head', 'emergency tiller on the stock head', 'open the bypass valve, then the emergency tiller'],
  ['Autopilot', 'a tiller pilot clips on', 'wheel pilot, or a drive on the quadrant', 'wheel pilot, or a drive on a tiller arm', 'a pump plumbed into the hoses'],
  ['Two steering positions', 'no', 'awkward', 'possible', 'easy: two pumps'],
  ['On the reference fleet', 'Sadler 32, Gib’Sea 31 {TWO}', 'Moody 33 {TWO}, most wheel boats', 'Gib’Sea 33 (Whitlock; rod or cable {TBC})', 'Finnsailer 35, both helms {TWO}'],
], wide=True)}

{card('deck--tiller', 'Tiller', 'tiller extension, tiller pilot', 'A wooden or aluminium lever fixed to the head of the rudder stock. Standard on the Sadler 32 and the Gib’Sea 31; some have been converted to wheels since.',
  ['Push the tiller to one side and the rudder swings the other way, so the boat turns towards the side you pushed away from. The feel is direct: every wave that hits the rudder reaches your hand.', 'An extension (a hinged rod on the end) lets one person steer from the side deck or while working a winch.'],
  ['The simplest, cheapest and most reliable steering there is, with nothing to inspect but the rudder itself.', 'Lifted at anchor, it leaves the whole cockpit free; a tiller pilot (a small electric autopilot, see Autopilots below) or a wind vane (self-steering driven by the wind) connects to it with a pin and a socket.'],
  ['It sweeps half the cockpit while sailing.', 'A “strong-arm job” in strong wind with the wind behind the side (a broad reach), and the reversed sense confuses beginners for a day or two.'],
  ['Play (loose movement) where the tiller fits the stock head; a split or rotten wooden tiller; worn rudder bearings felt as a knock. On the Gib’Sea 31 the rudder bearings are known to wear and give play at the tiller {ONE}.'],
  ['Waggle the tiller with the boat still: movement at the stock head or in the bearings is wear. Converting to a wheel costs several thousand pounds in parts alone {TWO} and adds everything the next four cards describe.'], fold=True)}

{figure('fig-wheel-steering', 'wheel steering', '0 0 900 470', 'Cable-and-chain wheel steering in an aft-cockpit boat, seen from the side', 'The stern of the boat with the bow to the right. A wheel on a pedestal in the cockpit turns a sprocket; a chain runs down inside the pedestal and becomes two wire cables that pass over sheaves and back to the two ends of a quadrant clamped to the rudder stock. Rudder stops sit either side of the quadrant, an autopilot ram pushes an arm on the stock, upper and lower bearings carry the stock, and a square socket on the stock head under a deck plate takes the emergency tiller. An inset shows the quadrant from above.', g.wheel_steering(), 'Bow to the right; the quadrant is drawn edge-on in the main view and from above in the inset. Wheel to sprocket to chain to two wires to quadrant to stock: every link in the chain is something a surveyor wants to see.')}

{card('deck--cable-steering', 'Wheel steering with cable and chain', 'Edson, Whitlock conduit, Lewmar', 'The wheel turns a sprocket in the pedestal; a short length of bicycle-type chain runs over it and each end of the chain becomes a wire cable. The two wires run down the pedestal, over sheaves (pulleys) or through plastic conduit, and back to the two ends of a quadrant on the rudder stock. Most wheel-steered boats of this class have it; on the Moody 33 the evidence points to Whitlock cable running in blue plastic conduit, though no source states what was fitted from new {TWO}.',
  ['Turn the wheel and one wire pulls while the other goes slack; the quadrant turns the stock. Rudder stops (blocks that the quadrant hits) limit the swing so that the chain can never run off the sprocket.', 'Tension is right when you cannot move the quadrant by hand with the wheel locked; over-tight cables make the helm feel dead and sticky through friction at the sheave axles.'],
  ['Cheap, light, widely understood and repairable by any yard. Edson and Lewmar still sell every part.', 'Good feel when correctly tensioned.'],
  ['Wire stretches and frays, sheaves seize, chain jumps if slack; the whole system lives out of sight under the cockpit.', 'A long run from a centre cockpit to a rudder under an aft cabin, as on the Moody 33, means more sheaves or conduit and more friction {TWO}.'],
  ['Broken strands (“meat hooks”) where the wire bends over a sheave; scored or grooved sheaves from misalignment; a wire that has worn a groove in its conduit so the helm goes stiff or locks solid (the Moody cure is brass conduit ends with grease points) {TWO}; a quadrant that moves on the stock because its clamp bolts or key (the small metal bar locking it to the stock) have worked loose; the worst single act is letting go of the wheel in reverse, which slams the rudder against the stops and can wreck the system.'],
  ['Once a year and before any long passage: run a clean rag along each wire and feel for snags; watch the chain roll over the sprocket as someone turns the wheel; with the rudder centred check the chain sits equally each side of the sprocket; have someone turn the wheel while you watch for movement between quadrant and stock; check the stops meet their supports on both sides; grease the sheave axles. Edson says replace the wire every five years.'], fold=True)}

{card('deck--rod-steering', 'Rod (mechanical) steering', 'Whitlock Cobra and Mamba, Jefa', 'Instead of chain and wire, a solid rod or tube joins a gearbox at the pedestal to a gearbox or lever at the rudder stock. Whitlock, a British maker now owned by Lewmar, made the two systems found on this class: the Cobra, with a rack-and-pinion head (a toothed wheel driving a toothed bar) turning a rod down the pedestal, connected to the stock by a drag link (a push-pull rod), and the Mamba, with bevel gearboxes and rotating torque tubes. The 2002 Gib’Sea 33 has a Whitlock wheel; whether it is Cobra rod or Whitlock cable is {TBC}.',
  ['The wheel shaft drives gears rather than a chain; the gears turn a rod or tube, and a lever at the bottom moves the rudder through a drag link with ball-jointed ends that take up small misalignments.'],
  ['Positive and precise, with no wire to stretch or fray and no cables to tension.', 'Compact under the cockpit.'],
  ['More expensive; needs its geometry kept in line; parts are specific to the system.', 'Owners complain that Lewmar publishes almost no maintenance information; independent specialists in the UK hold spares and make obsolete parts {TWO}.'],
  ['Rack and pinion wear (taken up by removing shims, thin spacer plates, where the wheel housing meets the pedestal); a cracked bevel-gearbox housing that lets the gears move; a “notchy” wheel from worn bevel gears; a split seal over the wheel-shaft bearings that lets them corrode; squeaks from the pedestal; and, in the worst cases reported, a helm that goes stiff and “within a quarter turn becomes locked solid” {TWO}.'],
  ['Turn the wheel from stop to stop with the boat still and feel for notches, tight spots and play; look for cracks in the cast metal gearbox housings and for movement at the rod ends; ask when it was last greased and by whom.'], fold=True)}

{card('deck--hydraulic-steering', 'Hydraulic steering', 'Vetus, helm pump, ram, bypass valve', 'Turning the wheel drives a small hand pump behind it; two hoses carry oil to a cylinder (the ram) that pushes a tiller arm on the rudder stock. The usual choice where a boat has two steering positions, because a second pump simply joins the same hoses: the Finnsailer 35 steers hydraulically from both its cockpit and its wheelhouse wheel, according to two sale listings {TWO}; the maker of its gear was not found {TBC}.',
  ['Oil pumped to one end of the ram pushes the piston, and the tiller arm, one way; turning the other way pumps it back. One-way (non-return) valves in the pumps let two helms share one ram.', 'A bypass valve joins the two sides of the ram, so oil flows freely from one to the other. Open, it disconnects the wheels completely: that is what lets the emergency tiller (or a wind vane or mechanical drive acting on the stock) move the rudder. Closed, the wheels steer, and so does a hydraulic autopilot pump plumbed into the hoses. Opened by mistake, it means no steering at all.'],
  ['Two or more steering positions with no mechanical linkage between them.', 'Few moving parts in the cockpit; the ram and hoses can go wherever there is room.'],
  ['No feel: you cannot sense weather helm or a stalling rudder (one turned so far that it stops gripping the water) through the wheel, and no fixed relationship between wheel and rudder position: the rudder angle cannot be read from the wheel.', 'Leaks at the ram’s end seals, air in the lines, and a rudder that wanders (“creeps”) when the valves that hold the oil in the pump when you let go of the wheel start to leak.'],
  ['Low oil, air in the system after a leak, weeping seals at the ram, a helm that keeps turning without moving the rudder.'],
  ['Check the reservoir level and look at the ram for oil; bleeding follows the maker’s sequence (Vetus: open the small bleed valves one at a time to let trapped air out, lowest helm first on twin helms); find the bypass valve and know which way is open; with it open and the boat still, move the rudder by hand to feel the bearings, then close it again before steering.'], fold=True)}

{figure('fig-hydraulic', 'hydraulic steering', '0 0 900 420', 'Hydraulic steering with two helms, as a schematic', 'A schematic. Two helm pumps, one in the wheelhouse and one in the cockpit, each with a wheel and lock valves, are joined by two hoses that run to a ram. The ram’s rod pushes a tiller arm on the rudder stock. Near the ram a bypass valve links the two hoses; open, it lets oil flow straight across so the wheels are disconnected and the emergency tiller can steer. A dashed autopilot pump is teed into the same hoses. Arrows show oil going to one end of the ram and back from the other.', g.hydraulic_steering(), 'Every system differs in its details (where the filler and vent are, whether there is a third line between the pumps): the manual for your gear is the reference. What every owner must know is where the bypass valve is, and which way is open.', note=HINT, start=0.72)}
{card('deck--emergency-tiller', 'Emergency tiller', 'the steering you have not tried', 'A bar that drops into a square socket on the head of the rudder stock, reached through a deck plate in the cockpit sole or, on a centre-cockpit boat, in the aft cabin. Every wheel-steered boat should carry one, and most owners have never fitted theirs.',
  ['When the chain, wire, rod or hydraulics fail, the stock is still connected to the rudder. The stock rises above the quadrant or ram and is squared to take the tiller.', 'On a Moody centre-cockpit boat the socket is in the aft cabin, and owners describe steering “with your foot, head out of the aft hatch”, with a second person on deck to look out {TWO}.'],
  ['Tested in harbour, it works under engine and lets you get home.'],
  ['Tested at sea, many turn out to be nearly useless: a magazine trial on a 12 m boat found the short bar “difficult to keep on course under sail without the judicious application of a foot”, and the professional advice is to test it in strong wind, with the wind from the side and from behind, not only in flat water. Where an autopilot drive acts directly on the quadrant, steering with the autopilot is often the better fallback.'],
  ['Tiller missing, rusted into its locker, the wrong size for the socket, or blocked by a deck plate that has not been opened in ten years; on hydraulic boats, a bypass valve nobody can find.'],
  ['Find it, fit it, and steer with it once a season in harbour and once under way; know where the bypass valve is on a hydraulic boat.'], kind='fault', fold=True)}

{card('deck--autopilot', 'Autopilots and wind vanes', 'tiller pilot, wheel pilot, below-deck drive', 'A tiller pilot is a self-contained ram that clips between the cockpit side and a pin on the tiller; a wheel pilot is a motor that drives the wheel through a belt and a clutch; a below-deck pilot drives the quadrant, a tiller arm or the hydraulics directly. All steer to a compass course or to the wind angle; none were fitted from new on any of the reference boats {TBC}.',
  ['The pilot compares the heading from its compass with the course you set, and moves the rudder to correct. A tiller pilot has the compass built into the unit in the cockpit; a below-deck pilot has a separate electronic compass (a fluxgate) mounted below decks away from iron.', 'Tiller pilots are rated by boat weight: the Raymarine ST2000 is for boats up to 4,500 kg and the smaller ST1000 up to 3,000 kg. The Sadler 32 weighs about 4,300 kg empty, so loaded for cruising it is at or over the ST2000’s limit: marginal, not comfortable. Below-deck drives that push in a straight line (linear drives) are the first choice for cable-and-quadrant boats; a hydraulic boat takes an electric pump that can pump either way, plumbed into its hoses.'],
  ['The most useful crew member on a short-handed cruise, and the reason a couple can sail a 10 m boat.'],
  ['A tiller pilot is exposed to spray and works hard on a heavy boat; a wheel pilot’s belt slips and the clutch that engages it with the wheel fills with dirt; a below-deck drive costs many times more and needs a bracket strong enough to steer the boat.', 'A fluxgate near the engine, the keel, the anchor chain or a loudspeaker steers a wandering course {TWO}.'],
  ['Slipping belts and dirty engaging clutches on wheel pilots; compass-circuit failures reported on older Raymarine units {TWO}; a tiller-pilot socket pulled out of a rotten cockpit coaming.'],
  ['A wind vane (Hydrovane, Aries, Monitor and others) steers to the wind with no electricity: a servo-pendulum type pulls lines to the boat’s own tiller or wheel, an auxiliary-rudder type such as the Hydrovane steers with its own small rudder and doubles as emergency steering. Blue-water gear, rare on coastal boats.'], fold=True)}
{sources('steering', [
  'Fleet: Moody 33 wheel steering per ' + a('https://www.listingsport.com/sailboats/moody/33-mk-ii','Listings Port') + ' and ' + a('https://www.moodyowners.org/Moody_Archives/19_boat.htm','the Moody archive (33S)') + '; Whitlock conduit inferred from ' + a('https://yachtsteeringservices.com/product-category/whitlock-lewmar-steering/moody-cable-steering-sets/','Yacht Steering Services’ Moody cable sets') + ' and a ' + a('https://forums.ybw.com/threads/stiff-steering-the-saga-continues.101200/','YBW thread on stiff Whitlock steering') + ' (anecdotal); emergency tiller in the aft cabin per ' + a('https://forums.ybw.com/threads/emergency-tiller.34126/','a YBW thread') + ' (anecdotal). Sadler 32 tiller per ' + a('https://boatsign.com/for-sale/sadler-32','Boatsign') + ' and ' + a('https://forums.ybw.com/threads/sadler-32-what-should-i-look-for.170275/','YBW owners') + '. Bavaria 1060 wheel per a ' + a('https://www.boats.com/sailing-boats/1985-bavaria-bavaria-1060-9991645/','1985 listing') + '. Gib’Sea 31 tiller and bearing wear per ' + a('https://www.listingsport.com/sailboats/gib-sea/31','Listings Port') + ' and ' + a('https://poole.boatshed.com/gib_sea_31-boat-22156.html','a Boatshed listing') + '. Gib’Sea 33 Whitlock wheel per the ' + a('https://www.boats.com/reviews/boats/gibsea-33-the-latest-from-dufour/','boats.com review') + '. Finnsailer 35 hydraulic twin helms per ' + a('https://dougedwardsyachts.co.uk/finnsailer-35/','Doug Edwards Yachts') + ' and ' + a('https://poole.boatshed.com/finnsailer_35-boat-152341.html','a Boatshed listing') + '.',
  'Tiller and wheel: ' + a('https://www.sailboat-cruising.com/Sailboat-Tillers-vs-Wheel-Steering.html','sailboat-cruising.com') + ', ' + a('https://no-frills-sailing.com/steering-wheels-vs-tiller/','No Frills Sailing') + '; conversion costs from ' + a('https://www.sailnet.com/threads/rough-cost-to-convert-tiller-to-wheel.95158/','SailNet') + ' (US, anecdotal).',
  'Cable and chain: ' + a('https://goodoldboat.com/steering-systems-101/','Good Old Boat, steering systems 101') + ', ' + a('https://edsonmarine.com/blog/steering-cable-tension/','Edson on cable tension') + ', ' + a('https://www.j109.org/docs/edson_steering_system_inspection_checklist.pdf','Edson inspection checklist') + ', ' + a('https://www.practical-sailor.com/systems-propulsion/steering-equipment-inspection/','Practical Sailor on steering inspection') + ', ' + a('https://www.spinsheet.com/upkeep-your-sailboat%E2%80%99s-steering-system','SpinSheet on rudder stops') + ', ' + a('https://www.cruisingworld.com/story/how-to/inspecting-sailboat-steering-system/','Cruising World on quadrant movement') + '.',
  'Rod: ' + a('https://www.practical-sailor.com/systems-propulsion/steady-at-the-helm/','Practical Sailor, steady at the helm') + ', ' + a('https://www.boats.com/reviews/whitlock-mamba-drives/','boats.com on the Mamba') + ', ' + a('https://www.lewmar.com/cobra-steering','Lewmar Cobra page') + '; wear points and spares from ' + a('https://forums.ybw.com/threads/whitlock-cobra-repairs-and-maintenance.515955/','YBW threads') + ' (anecdotal) and ' + a('https://yachtsteeringservices.com/product-category/whitlock-lewmar-steering/','Yacht Steering Services') + '.',
  'Hydraulic: ' + a('https://vetus.com/wp-content/uploads/020105.03-r05-2022-01-MTC30_175.pdf','Vetus installation manual') + ', ' + a('https://www.vetus-shop.com/files/Vetus_Filling_Bleeding.pdf','Vetus filling and bleeding') + ', ' + a('https://www.boats.net/blog/troubleshooting-hydraulic-steering-system-problems','boats.net on hydraulic faults') + '.',
  'Emergency tillers: ' + a('https://www.pbo.co.uk/seamanship/using-an-emergency-tiller-25196','PBO, using an emergency tiller') + ', ' + a('https://www.morganscloud.com/2012/05/02/emergency-tillers-easier-said-than-done/','Attainable Adventure Cruising') + ', ' + a('https://www.yachtingworld.com/features/how-to-set-up-emergency-steering-system-129113','Yachting World') + '. Autopilots: ' + a('https://hudsonmarine.co.uk/products/raymarine-st2000-plus-cockpit-tiller-autopilot-maximum-displacement-4-500-kg-a12005','Raymarine ST2000 rating') + ', ' + a('https://www.raymarine.com/en-us/learning/online-guides/selecting-your-raymarine-drive-unit','Raymarine on drive units') + ', ' + a('https://www.sailboat-cruising.com/Wheel-Steering-Autopilots.html','on wheel pilots') + '; fluxgate and compass faults from ' + a('https://www.cruisersforum.com/forums/f13/raymarine-autopilot-fluxgate-compass-problem-277641.html','forum threads') + ' (anecdotal). Wind vanes: ' + a('https://www.pbo.co.uk/gear/windvane-self-steering-a-complete-guide-for-sailors-90435','PBO complete guide') + '.'
])}
{photo('deck-tiller-pilot.jpg', 'A black tiller pilot on a yacht’s cockpit seat, its push rod reaching towards the tiller, with its power lead', 'A tiller pilot (a Raymarine ST1000) on a small yacht: a peg at one end fits a socket in the cockpit seat, and the push rod at the other end moves the tiller.', 'Ilmari Karonen', 'public domain', '', 'https://commons.wikimedia.org/wiki/File:Boat_autopilot.jpg', 480, 640)}

  <h3>Anchoring gear</h3>
  <p>The anchor is the one piece of equipment that keeps the boat and its crew safe when everything else has stopped working, and the fittings it runs through take the biggest loads on the deck. The drawing shows the foredeck of a typical boat; the second one shows what the anchor itself looks like and how much chain to put out.</p>

{figure('fig-anchor-gear', 'anchor gear', '0 0 900 360', 'Anchor gear on the foredeck, seen from the side', 'The bow of the boat with the bow to the right. A plough anchor sits on the bow roller at the stem; its chain runs aft over a chain stopper and the gypsy of a windlass, then drops through the navel pipe into the chain locker below the deck. A snubber rope runs from a hook on the chain to a cleat, and a fairlead sits at the deck edge.', g.anchor_gear(), 'Bow to the right; the anchor is shown stowed. Once it is down, the chain’s load should end at the chain stopper, or at a cleat through a snubber (a stretchy rope hooked to the chain, see the chain card), never at the windlass. A swivel between chain and anchor is optional and adds a weak link.')}

{card('deck--windlass', 'Windlass', 'anchor winch, gypsy', 'A winch for anchor chain, manual or electric, horizontal (motor and gearbox on deck in one casing) or vertical (motor below deck). Its gypsy is machined for one exact chain size and pattern, so chain and gypsy must match. None of the reference boats had one as standard as far as the sources show; the Gib’Sea 33 offered an electric one as an option and most older boats have had one retrofitted {TWO}.',
  ['The gypsy’s notches grip the chain links and haul them in; the chain then falls into the locker through the navel pipe. A horizontal windlass wraps the chain a quarter turn and needs about 300 mm of fall to the chain pile; a vertical one wraps half a turn, grips better and needs about 450 mm.', 'Sizing rule: add up the weight of anchor, chain and rope and choose a windlass whose pull is at least three times that. Electric units draw 60 to 120 amps at full load through heavy cable and a circuit breaker by the battery.'],
  ['Anchoring becomes a one-person job at any age or strength, so you anchor more often and more safely.'],
  ['Weight in the bow, a big electrical load (the Systems section covers wiring), and a gearbox in the wettest place on the boat.', 'A windlass is a winch, not a mooring point: chain left on the gypsy in a swell snatches at the shaft and can bend it. The load goes to a chain stopper or a cleat.'],
  ['Chain that jumps the gypsy because it is the wrong calibration; a stuck gypsy clutch (the release that lets the chain run out freely); corroded motor terminals in the locker; a chain pile that jams under the navel pipe; a solenoid (the electric switch for the motor) that sticks on.'],
  ['Match the chain to the size stamped on the gypsy: there are two common standards, ISO 4565 and DIN 766, whose links differ slightly in length (the pitch), so 8 mm of one does not fit a gypsy made for 8 mm of the other; check the breaker and the cable size; wash the salt off the gypsy and clutch; never anchor on the windlass alone.'], fold=True)}

{card('deck--chain', 'Chain, rode and snubber', 'calibrated chain, scope, catenary', 'The rode is whatever joins anchor to boat: all chain on most European cruising boats of this size, or chain with rope behind it. Calibrated chain is made to a standard link size so that it fits a gypsy. The snubber is a short length of stretchy nylon rope from a hook on the chain to a cleat that takes the load off the windlass and stops the chain snatching.',
  ['Chain hangs in a curve (the catenary) and its weight pulls the anchor along the seabed rather than up; more chain out, called more scope, means a flatter pull and a better-set anchor. Yachting Monthly’s rule of thumb, for water up to about 10 m deep, is chain length in metres equal to the wind speed in knots plus the boat’s length in metres: about 26 m for a 10 m yacht in a Force 4 (16 knots), about 43 m in a Force 7 (33 knots). Other guides put it as a ratio of chain to depth, counting the height of the bow above the water: commonly four or five to one in settled weather {TWO}, six to one or more in strong wind.', 'Size: 8 mm chain is the usual fit up to about 9.4 m of boat and 10 mm up to about 11.9 m, going up a size for a heavy boat; 8 mm calibrated chain weighs about 1.45 kg per metre with a breaking load around 3,200 kg. A 10 m, 5-tonne boat sits on the boundary and owners argue about it endlessly {TWO}.'],
  ['All chain cannot chafe through on rock and its weight is the shock absorber.'],
  ['Weight in the bow: 50 m of 10 mm chain is about 115 kg.', 'A kellet (a weight slid down the chain) adds little that more chain and a snubber do not, and is “properly retired” in the view of Practical Sailor.'],
  ['Rusted, elongated or stiff links; a worn joint where rope is woven into the end of the chain (a splice); a chain marked in a way nobody on board understands; a snubber with no chafe protection at the bow roller.'],
  ['Mark the chain every 10 m; turn it end for end every few seasons so the wear spreads; a snubber long enough to stretch, led through the roller or a fairlead with chafe cover.'], fold=True)}

{figure('fig-anchors', 'anchor types', '0 0 900 340', 'Four anchor families and how much chain to put out', 'Left: silhouettes of a plough anchor (CQR, Delta), a claw (Bruce), a new-generation scoop with a roll bar (Rocna, Spade, Mantus) and a flat fluke anchor (Danforth, Fortress). Right: a boat at anchor with its chain hanging in a curve to an anchor set on the seabed, a dimension for the depth and the chain labelled along its curve, drawn to about four and a half times the depth, and a depth arrow from the bow roller to the seabed.', g.anchors(), 'Independent tests put the new-generation scoop anchors at the top for holding in sand and mud, the Delta in the middle, and the CQR and Bruce at the bottom; but results depend on the seabed, and in very soft mud some roll-bar anchors have failed to set at all.', start=1)}

{compare('Anchor types at a glance', ['', 'Plough', 'Claw', 'Scoop (new generation)', 'Flat fluke'], [
  ['Holding in sand and firm mud', 'fair', 'poor to fair', 'best', 'very good'],
  ['In soft mud', 'fair', 'poor', 'varies: some roll-bar designs fail to set', 'very good'],
  ['In weed and rock', 'fair', 'fair', 'good', 'poor'],
  ['On a bow roller', 'stows well', 'stows well', 'roll bar can be awkward', 'awkward; usually a kedge in a locker'],
  ['Examples', 'CQR, Delta', 'Bruce', 'Spade, Rocna, Mantus, Ultra', 'Danforth, Fortress'],
])}

{card('deck--anchors', 'Anchors', 'CQR, Delta, Bruce, Rocna, Spade, Fortress', 'Four families are drawn above. The plough (CQR with its hinged shank, or arm, and the one-piece Delta) and the claw (Bruce) are what boats of this age left the factory with: an 11 kg CQR is typical on the Sadler 32 and was on a Gib’Sea 31 with a smaller kedge {TWO}. The new-generation scoop anchors (the Spade from 1996, the Rocna from 2004, then Mantus, Ultra and others) hold far better for their weight. Flat fluke anchors (Danforth, Fortress) hold superbly in sand and mud, fold flat, and are the usual second (kedge) anchor.',
  ['An anchor works by digging in, not by weight: the tip has to penetrate and the fluke (the flat blade that digs in) has to turn into the seabed as the chain pulls along the bottom. Roll bars (a hoop over the fluke) and weighted tips make new designs land the right way up and dig in at once.', 'Independent tests (Yachting Monthly 2006, West Marine 2006 and later, Practical Sailor, PBO) mostly agree on the order in sand and firm mud: new generation first, Delta in the middle, CQR and Bruce last. In very soft mud Practical Sailor found a Rocna “did not set at all” while a weighted-tip Manson did better, so keep a fluke anchor for soft bottoms.'],
  ['A modern anchor one size heavier than the boat needs is the cheapest insurance on the boat. For a 10 to 11 m boat Practical Sailor suggests about 13.6 kg of modern anchor {ONE}; makers’ own tables should be checked before buying.'],
  ['A CQR or Bruce sized for the boat in 1980 is a fair-weather anchor by today’s standards.', 'Roll-bar anchors are awkward on some bow rollers; swivels between chain and anchor add a weak link.'],
  ['A bent shank (the anchor’s arm) from being pulled out of the seabed sideways; a worn or stuck hinge on a CQR; the zinc coating (galvanising) gone, leaving bare rust; a shackle with no wire binding its pin shut.'],
  ['Look at the anchor that comes with the boat and budget to replace it; carry a kedge; bind every shackle pin shut with a few turns of stainless wire (seizing it) so it cannot unscrew.'], fold=True)}

{card('deck--cleats', 'Bow roller, cleats and fairleads', 'bow fittings', 'The bow roller is the fitting at the stem that the chain runs over and the anchor stows on. Cleats are what mooring lines and the snubber are tied to; fairleads guide a rope over the deck edge without holding it. These take the biggest loads on the boat: a yacht jerking at anchor or against a floating jetty (a pontoon) in a gale puts tonnes into one cleat.',
  ['A horn cleat takes a figure-of-eight of rope; the load pulls sideways and upwards at once, so its bolts are pulled sideways (shear) and upward (tension) together and the deck under it needs a backing plate. Yachting Monthly’s rule of thumb: 25 mm of cleat length for every 1.5 mm of rope diameter, so a 14 mm mooring line wants a cleat about 230 mm long.', 'In a BoatUS test of cleat assemblies, failures came between 540 and 3,400 kg of pull and 57% of them were at the fasteners, not the cleat.'],
  ['Simple, visible and easy to upgrade.'],
  ['On a cored deck a proper backing plate means cutting away and sealing the core, which is why so many boats have a few washers instead.'],
  ['A cleat that rocks; crazed gelcoat around a cleat or the bow roller; a roller that has worn flat or will not turn; a bow roller with no pin over the chain, so it jumps out in a swell.'],
  ['Push and pull every cleat; look underneath for a backing plate; check the bow roller turns and has a retaining pin.'], fold=True)}
{sources('anchoring gear', [
  'Windlass: ' + a('https://www.westmarine.com/west-advisor/Selecting-An-Anchor-Windlass.html','West Marine on selecting a windlass') + ', ' + a('https://www.mauripro.com/blogs/anchoring-docking-windlasses/lewmar-windlasses-horizontal-vs-vertical','MAURIPRO on horizontal vs vertical') + ', ' + a('https://www.fisheriessupply.com/using-your-windlass','Fisheries Supply on using a windlass') + ', ' + a('https://jimmygreen.com/a-guide-to-anchor-chain-snubbing/','Jimmy Green on snubbing') + '. Chain calibration: ' + a('https://www.mauripro.com/blogs/anchoring-docking-anchoring-equipment/chain-dimensions-choose-the-best-one-for-your-needs','MAURIPRO on chain dimensions') + ', ' + a('https://www.williamhackett.com/en-gb/files/1744367716_a5aacb581620767160af.pdf','William Hackett chain data') + '.',
  'Chain size and length: ' + a('https://jimmygreen.com/knowledge-centre/anchor-chain-and-rope-size-guide/','Jimmy Green size guide') + ', ' + a('https://www.duncanyacht.co.uk/index.php?route=product/product&path=2_3_6&product_id=1685','Duncan Yacht chain data (weight and breaking load)') + ', ' + a('https://www.yachtingmonthly.com/sailing-skills/how-much-anchor-chain-70603','Yachting Monthly, how much anchor chain') + ', ' + a('https://www.practical-sailor.com/sails-rigging-deckgear/assessing-the-anchor-kellet/','Practical Sailor on kellets') + '; the 8 vs 10 mm debate from ' + a('https://forums.ybw.com/threads/anchor-chain-8mm-or-10mm.620387/','YBW') + ' (anecdotal).',
  'Anchors: ' + a('https://www.westmarine.com/west-advisor/Anchor-Testing.html','West Marine anchor tests') + ', ' + a('https://www.practical-sailor.com/sails-rigging-deckgear/anchoring-in-squishy-bottoms/','Practical Sailor in soft mud') + ', ' + a('https://www.practical-sailor.com/blog/roll-bar-anchors-in-mud/','Practical Sailor, roll-bar anchors in mud') + ', ' + a('https://www.yachtingmonthly.com/gear/best-anchors-8-new-generation-designs-suitable-for-every-boat-83917','Yachting Monthly, eight new-generation designs') + ', ' + a('https://www.petersmith.net.nz/boat-anchors/independent-performance-testing.php','a summary of independent tests by the Rocna designer (partial)') + '; sizing from ' + a('https://www.practical-sailor.com/sails-rigging-deckgear/selecting-the-right-anchor-size/','Practical Sailor') + ' (single source). Fleet anchors: ' + a('https://www.mcyachts.co.uk/boats-for-sale/sadler-32/2677150/','a Sadler 32 listing') + ', ' + a('https://poole.boatshed.com/gib_sea_31-boat-22156.html','a Gib’Sea 31 listing') + ' (one boat each).',
  'Cleats: ' + a('https://www.yachtingmonthly.com/gear/bow-roller-cleats-strong-enough-49455','Yachting Monthly, are your bow roller and cleats strong enough') + ', ' + a('https://www.boatus.org/findings/16','BoatUS Foundation cleat test') + ', ' + a('https://www.practical-sailor.com/boat-maintenance/how-big-does-a-backing-plate-need-to-be/','Practical Sailor on backing plates') + '.'
])}

  <h3>Winches, clutches and tracks</h3>
{figure('fig-winch', 'winch and clutch', '0 0 900 340', 'A self-tailing winch cut open, a rope clutch and a horn cleat', 'Left: a winch in section showing the drum, the self-tailing jaws and stripper arm on top, the handle socket, the gears inside and the pawls at the base. Middle: a rope clutch with its toothed cam, lever and the rope passing through to a winch. Right: a horn cleat on a deck with a backing plate and an arrow showing the direction of a mooring load.', g.winch(), 'The winch multiplies your pull; the clutch holds the rope so the winch can do the next job; the cleat takes the loads that would tear anything else off the deck.')}

{card('deck--winches', 'Winches', 'Lewmar, Barlow, Barient, Andersen, Harken, Gibb', 'A drum you wind rope around and turn with a handle. On modern Lewmar and Harken winches the size number is the power ratio: a size 40 gives roughly 40 kg of pull on the rope for 1 kg on a standard 254 mm handle (in practice nearer 32 in top gear of a two-speed). Older winches of this fleet’s era (Barlow, Gibb, early Lewmar) were numbered differently, so compare them by drum size, not number. Two-speed winches change gear when you wind the other way. Lewmar is the make found on most of the reference fleet in listings, with size 40 primaries on a Moody 33 Mk II (the second version) and self-tailing (ST) size 30 primaries with a size 16 self-tailing halyard winch on a 2002 Gib’Sea 33 {TWO}; the original fit on the other boats was not found.',
  ['Gears in the base multiply the handle’s turns; pawls, small spring-loaded catches, let the drum turn one way and lock the other. Self-tailing jaws on top grip the rope tail so one person can wind with both hands.', 'Genoa winches are sized from the sail area; the highest load comes with a reefed headsail in strong wind.'],
  ['A well-made bronze or stainless winch lasts the life of the boat if it is serviced; Lewmar and Andersen still supply parts, and Lewmar took over Barient and Barlow spares.'],
  ['A winch that has never been opened is full of dried grease and salt; a missing pawl spring lets the drum spin backwards under load, which breaks fingers.'],
  ['Drum that spins freely both ways (pawl springs); grinding or stiff turning (dried grease, corroded bearings); a self-tailing jaw worn smooth; cracks at the base bolts.'],
  ['Once a year: remove the spring clip (circlip) or split rings (collets) that hold the drum on, lift the drum, wash the gears and pawls in degreaser, fit new pawl springs, light machine oil on the pawls (never grease, which stiffens them), a thin film of winch grease on the gears and bearings, and rebuild. A universal service kit costs a few tens of pounds {TWO}; Lewmar suggests new pawls every five years.'], fold=True)}
{photo('deck-self-tailing-winch.jpg', 'A grey self-tailing winch with a red sheet wound round its drum and led into the jaws on top, and a winch handle fitted', 'A self-tailing winch: the sheet goes clockwise round the drum and into the jaws on top, which hold it while you wind the handle.', 'ThoKay', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0', 'https://commons.wikimedia.org/wiki/File:Self-tailing_Winch.jpg', 707, 900)}

{card('deck--clutches', 'Clutches, cleats, cams and clams', 'rope clutch, cam cleat, clam cleat', 'Four ways of holding a rope. A horn cleat takes a figure-of-eight and holds anything. A rope clutch closes a toothed cam onto the rope when its lever is pushed down, and holds far more than a cam cleat, though less than the rope itself will take; it lets you take the rope off the winch and use the winch for something else. A cam cleat has two spring-loaded jaws and releases with a flick, for sheets and the small ropes that adjust sails (control lines) under hand load. A clam cleat is a ridged slot the rope wedges into: compact, but hard to release under load.',
  ['A clutch holds by friction from teeth pressing the rope onto a base; it releases by lifting the lever, which under heavy load must be done with the rope back on the winch or the rope will run and burn.'],
  ['Clutches let a short-handed crew run every halyard and reefing line to one or two winches by the companionway.'],
  ['Worn clutch cams let the rope creep and chew its cover; every rope that passes through a clutch chafes at that spot.'],
  ['Creeping halyards; a rope with a flat, shiny patch where it sits in the clutch; a cam cleat whose springs have gone soft.'],
  ['Open the clutch, look at the teeth, and check the rope where it sits; move halyards a few centimetres so the wear spreads.'], fold=True)}

{card('deck--tracks', 'Tracks, cars and blocks', 'genoa track, pin-stop car, ball-bearing car, traveller', 'The genoa sheet runs through a car, a sliding block on a track along the side deck; the mainsheet runs to a car on the traveller track across the cockpit. Blocks are pulleys: plain-bearing ones for static or heavy loads, ball-bearing ones for lines that run.',
  ['A pin-stop car is held by a spring pin in holes along the track and can only be moved when the sheet is slack, which means after a tack. A ball-bearing car with a control line moves under load from the cockpit; both run on the same track, so an upgrade is easy.'],
  ['Cheap, robust and simple to replace piece by piece.'],
  ['Plastic sheaves and car wheels go brittle in the sun after decades; a seized car cannot be moved when you need it.'],
  ['Cars that will not slide; tracks with corroded or missing screws; blocks with cracked side plates (cheeks) or oval holes; a traveller car whose bearings have spilled.'],
  ['Move every car and turn every block by hand; tracks are through-bolted and are as much a leak path as any other fitting.'], fold=True)}
{sources('winches and deck gear', [
  'Winches: ' + a('https://www.mauripro.com/blogs/how-tos/how-to-choose-your-harken-winches-1','MAURIPRO on choosing Harken winches (power ratio)') + ', ' + a('https://medusamarine.co.uk/index.php/numbers-mean-winches-different-old-winches/','Medusa Marine on winch numbers') + ', ' + a('https://www.yachtingmonthly.com/gear/servicing-winches-an-experts-guide-73141','Yachting Monthly, servicing winches') + ', ' + a('https://www.pbo.co.uk/expert-advice/winch-servicing-step-by-step-maintenance-guide-106882','PBO winch servicing guide') + ', ' + a('https://sailboatrefit.com/how-to-service-a-lewmar-winch/','on servicing a Lewmar winch (pawls every five years)') + ', ' + a('https://www.morganscloud.com/jhhtips/qa-winch-service-intervals-grease/','Attainable Adventure Cruising on intervals') + '; spares: ' + a('https://us.binnacle.com/lewmar-bt00209-barient-barlow-pawl-spring','Barient and Barlow springs under Lewmar numbers') + '. Fleet winches from ' + a('https://www.rightboat.com/boats-for-sale/moody/33-mk-ii/rb623507','a Moody 33 Mk II listing') + ' and ' + a('https://www.devalk.nl/en/yachtbrokerage/203006/GIB-SEA-33.html','a 2002 Gib’Sea 33 listing') + ' (one boat each).',
  'Clutches and cleats: ' + a('https://www.yachtingmonthly.com/gear/cleats-clutches-and-jammers-which-to-use-and-when-88277','Yachting Monthly, cleats, clutches and jammers') + '. Tracks and blocks: ' + a('https://www.harken.com/en/how-to-choose/ordering-travelers-genoa-lead-cars/','Harken on genoa cars') + ', ' + a('https://marine.wichard.com/en/news/plain-bearing-ball-bearing-and-roller-blocks-how-should-i-choose-a-type-of-block','Wichard on block bearings') + '.'
])}

  <h3>Guardrails, stanchions and staying aboard</h3>
{card('deck--guardrails', 'Stanchions, guardrails and jackstays', 'lifelines, pulpit, pushpit, pelican hook', 'Stanchions are the posts along the deck edge; the guardrails (lifelines in America) are the two wires they carry, from the pulpit at the bow to the pushpit at the stern. Jackstays are webbing straps along each side deck that you clip your harness to. The racing rules, which most cruisers follow, ask for an upper rail at least 600 mm above the deck with no gap over 560 mm.',
  ['A stanchion is a lever: a body falling against the top of a 600 mm post puts several times its weight into the base bolts, which is why bases are through-bolted with backing plates and why levered bases are the commonest deck leak.', 'A gate in the rail closes with a pelican hook, a hinged hook with a sliding keeper.'],
  ['Guardrails keep children, dogs and tired crew on the boat; jackstays keep a clipped-on crew member on it in bad weather.'],
  ['Plastic-covered wire hides its own corrosion: water gets in where the cover chafes at each stanchion and the wire rusts inside, invisibly, which is why racing rules now ban covered wire. Bare wire or Dyneema rope can be inspected.', 'Webbing jackstays lose strength in sunlight, gradually and relentlessly; UK suppliers suggest about five years, professional codes inspect them every six or twelve months.'],
  ['Rust weeping from under a plastic cover; a stanchion that moves when pushed or a base that has begun to lift; cracked or crazed gelcoat around a base; a pelican hook that will not close; faded, stiff or fraying jackstays.'],
  ['Push every stanchion hard; look under each base from inside the boat; replace covered wire with bare or Dyneema when it is due; stow jackstays below when the boat is not sailing.'], fold=True)}
{sources('guardrails', [
  a('https://www.ussailing.org/wp-content/uploads/2018/01/ISAF-Mo3-extract-with-US-Prescriptions.pdf','World Sailing Offshore Special Regulations, lifelines') + ', ' + a('https://www.cruisingworld.com/how-to/the-lifeline-quandary/','Cruising World, the lifeline quandary') + ', ' + a('https://www.practical-sailor.com/safety-seamanship/fiber-lifeline-protection-plan/','Practical Sailor on fibre lifelines') + ', ' + a('https://www.oceanmarinesurveyors.com/deck-hardware-stanchions-rails/','a surveyor on stanchion bases') + ', ' + a('https://jimmygreen.com/knowledge-centre/webbing-jackstays-guidance/','Jimmy Green on jackstay life') + '.'
])}

  <h3>Keeping the water out</h3>
  <p>Almost every deck on this class is a sandwich with a balsa or plywood core, and every fitting is bolted through it. The bedding under a fitting has no fixed life; owners talk of ten to twenty years {TWO}, and the boats are forty. So the questions are how a fitting should be bedded, how windows and hatches leak, and where the water shows up.</p>

{figure('fig-deck-fittings', 'deck fittings', '0 0 900 400', 'A properly bedded deck fitting, a stanchion with guardrails, and framed and bonded windows', 'Three panels. Left: a section through a cored deck with a fitting bolted through it; the hole through the core is filled with an epoxy ring, the fitting sits on a sealant bed with a countersink around the bolt, and a backing plate, washer and nut are underneath. Middle: a stanchion on a through-bolted base with upper and lower guardrails, a gate with a pelican hook and the toe rail at the deck edge; the leak path at a levered base is marked. Right: sections through a cabin side showing a framed window with aluminium frames and a rubber gasket, and a bonded acrylic pane glued to the outside.', g.deck_fittings(), 'The epoxy ring is the difference between a fitting that leaks onto the cabin sole and one that rots the deck. Both windows leak in the end; the framed one at its gasket and frame, the bonded one when the pane crazes or the glue lets go.')}

{card('deck--rebedding', 'Bedding and re-bedding a fitting', 'butyl, polyurethane, polysulphide, silicone, epoxy ring', 'Every fitting through the deck sits on a bed of sealant. The fault is not that the sealant fails, which it will, but that on a cored deck the water then runs down the bolt into the core. The cure, drawn above, is to seal the core before the fitting goes back on.',
  ['Drill each bolt hole oversize, scrape the core back between the skins, fill the hole with thickened epoxy and redrill through the plug: the bolt now passes through solid epoxy and a failed seal drips into the cabin instead of the core. Countersink the top of each hole (widen it into a shallow cone) so that a ring of sealant sits around the bolt where it cannot be squeezed out. Bed the fitting, tighten gently, and tighten again after the sealant has settled.', 'Which sealant: butyl tape for bedding fittings (never hardens, comes apart again, no cure time, no adhesion); polyurethane (Sikaflex 291, 3M 5200) where you want a near-permanent glued joint and will never want it off; polysulphide for above and below the waterline but not on plastic glazing; silicone only for acrylic and polycarbonate glazing, because nothing else will ever stick where silicone has been. Plastic windows take Sikaflex 295 UV with its primer, not 291, which cracks acrylic.'],
  ['Done once, properly, it outlives the sealant and the owner.'],
  ['Slow: a stanchion base is an hour, a whole deck is a winter.'],
  ['Stains and drips on the cabin ceiling under a fitting; weeping around bolt heads inside lockers; fittings that keep coming loose; a soft deck around the base; on the Moody 33 and Sadler 32 the classic leaks are at the chainplate cover plates and the coachroof windows {TWO}.'],
  ['Tap and press around every fitting; where a fitting has to come off anyway, do the epoxy ring while it is off; keep silicone off anything you may one day want to re-bed.'], kind='fault', fold=True)}

{card('deck--windows', 'Windows, portlights and hatches', 'portlights (small windows, often opening), framed, bonded, Houdini, Lewmar', 'Boats of this age have aluminium-framed windows with a rubber gasket around the pane and a bed of sealant between frame and cabin side, and aluminium-framed hatches with acrylic (Perspex) lids. Both leak when they are forty. The Moody 33’s large coachroof windows are the best-known case: they leak when the original rubber seals harden and crack (perish) and re-bedding them is “a common but labour-intensive DIY task” {ONE}; the Sadler 32 has small portlights that leak as well {TWO}; the Bavaria 1060 has acrylic windows of unknown construction {ONE}.',
  ['A framed window leaks in two places: between pane and frame when the gasket hardens, and between frame and cabin when the bedding fails, often at the frame bolts. A bonded window has no frame: a thick acrylic pane is glued to the outside of the cabin with a flexible adhesive, and fails when the pane crazes (a web of fine cracks from sun, stress and harsh cleaners) or the adhesive lets go at an edge.', 'Hatch lids are acrylic, not polycarbonate: acrylic resists sun and scratches, polycarbonate is tougher but fogs and yellows. Lids craze faster than portlights because they face the sky.'],
  ['A re-glazed framed window with a new gasket and fresh bedding is good for another twenty years; Lewmar, Gebo and Goiot still supply seals and lids for many hatches, and specialist firms refurbish them.'],
  ['Houdini hatches, common on 1970s and 1980s British boats, have toughened glass sprung into an aluminium frame. A leak round the opening lid is cured with a new hatch seal, which the maker sells; a leak between the glass and the frame cannot be resealed, the maker says, so that hatch is replaced whole, at about £300 to £350 each {TWO}. Lewmar seal kits run to a few tens of pounds; having the maker fit a new acrylic lid pane costs a few hundred {TWO}.'],
  ['Crazed or milky acrylic; a lid that no longer seals; water stains on the ply lining below a window; a frame that rocks when pushed; bubbles in the pane’s bonded edge.'],
  ['Hose the boat down and sit inside with a torch; press each pane and frame; read the maker’s name off the hatch before assuming spares exist.'], kind='fault', fold=True)}

{card('deck--cockpit', 'Sprayhood, cockpit drains, lockers and gas locker', 'dodger, self-draining gas locker', 'The sprayhood is the folding canvas hood over the companionway; cockpit drains empty the cockpit overboard; cockpit lockers open into the hull; and the gas locker is a sealed box that drains any leaking gas over the side, not into the boat.',
  ['Cockpit drains work by gravity. The European standard (ISO 11812) sizes them by the time a full cockpit takes to empty, with limits that depend on the boat’s design category (the CE rating for how rough the water it is built for is); owners suggest a bore of at least 40 mm {TWO} and no dips in the hose where water can sit; crossed drains stop the leeward one back-flooding when heeled.', 'The gas locker must be gas-tight up to at least the height of the cylinder valve, open only from the top, and drain from its base through a pipe of at least 19 mm bore falling continuously to a skin fitting above the waterline, with the cylinder at least a metre from any opening into the cabin (ISO 10239). The UK’s Boat Safety Scheme applies the same rule, but only on inland waterways.'],
  ['A good sprayhood is the difference between a wet crew and a dry one and is the first thing new owners replace: about £1,500 for a 9.8 m boat in 2025, from about £450 for new canvas on an existing frame {TWO}.'],
  ['Cockpit lockers are holes into the hull: a locker lid without a good gasket floods the boat when a wave fills the cockpit, and lockers full of gear block the drains and the engine.'],
  ['Drains that gurgle and hold water; a gas-locker drain hose blocked, kinked or perished (the hose has a limited life); a locker lid whose hinges and seal have gone; a sprayhood with cracked windows and rotten stitching.'],
  ['Pour a bucket into the cockpit and time it; put a hose down the gas-locker drain and watch it come out over the side; sit on each locker lid and look at its seal.'], fold=True)}

{card('deck--teak', 'Teak decks and non-slip', 'screwed and glued, Treadmaster, KiwiGrip', 'Most boats of this class have moulded GRP non-slip; a few, and many motorsailers, have teak laid over it. Whether the Finnsailer 35 was built with teak decks was not confirmed by any source {TBC}.',
  ['Traditional teak decks are glued and screwed: hundreds of screws under the caulking (the black rubbery filling between the planks), each a path for water into the deck below once the planks wear thin and the seams lift. Modern decks are glued only, about 8 mm thick.', 'Moulded non-slip wears smooth; it can be renewed with a rolled-on textured paint (KiwiGrip did best among single-part coatings in Practical Sailor’s ten-year test) or with glued sheet such as Treadmaster, which eventually lifts at the edges.'],
  ['Teak looks and feels wonderful and is cool and grippy wet or dry.'],
  ['Replacing a worn teak deck is the most expensive job on a boat of this size: owners quote £25,000 to £35,000 for new teak and about £10,000 for a synthetic deck on a 10.7 m boat {TWO}.'],
  ['Screw heads showing through worn planks; lifting seams; planks that move underfoot; black staining and softness around fittings, which usually means the plywood or core beneath has rotted.'],
  ['On a teak-decked boat, tap and press every plank and read the survey twice; on a moulded deck, walk it barefoot and look for smooth, shiny wear on the working areas.'], kind='fault', fold=True)}
{sources('keeping the water out', [
  'Bedding: ' + a('https://marinehowto.com/sealing-deck-penetrations-to-prevent-core-rot/','Marine How To, sealing deck penetrations (the epoxy-ring method)') + ', ' + a('https://marinehowto.com/bed-it-tape/','Marine How To on butyl') + ', ' + a('https://www.sailrite.com/Bedding-Deck-Hardware-Silicone-vs-Butyl-Tape','Sailrite, silicone vs butyl') + ', ' + a('https://www.boats.net/blog/rebedding-deck-hardware-sealants-guide','boats.net sealant guide') + ', ' + a('https://themarineking.com/blogs/news/sikaflex-291-vs-295','on Sikaflex 291 vs 295 UV') + ', ' + a('https://www.practical-sailor.com/boat-maintenance/marine-sealant-adhesion-tests/','Practical Sailor adhesion tests') + '.',
  'Windows and hatches: ' + a('https://www.listingsport.com/sailboats/moody/33-mk-ii','Listings Port on Moody 33 windows') + ', ' + a('https://forums.ybw.com/threads/moody-window-leaks.50516/','YBW, Moody window leaks') + ' (anecdotal), ' + a('https://hatchmasters.com/acrylic-vs-polycarbonate/','Hatchmasters, acrylic vs polycarbonate') + ', ' + a('https://www.pbo.co.uk/expert-advice/boat-hatch-replacement-fixing-a-cracked-lens-92111','PBO on a cracked hatch lens') + ', ' + a('https://forums.ybw.com/threads/leaking-houdini-hatches.156085/','YBW on Houdini hatches') + ' and ' + a('https://www.houdini-marine.co.uk/spares','Houdini Marine spares') + ', ' + a('https://www.yachtingmonthly.com/gear/how-to-repair-yacht-hatches-and-windows-94353','Yachting Monthly, repairing hatches and windows') + '.',
  'Cockpit and gas: ' + a('https://www.en-standard.eu/csn-en-iso-11812-small-craft-watertight-cockpits-and-quick-draining-cockpits/','ISO 11812 summary') + ', ' + a('https://forums.ybw.com/threads/cockpit-drains.43623/','YBW on cockpit drains') + ' (anecdotal), ' + a('https://www.rya.org.uk/water-safety/gas-safety/gas-safety-regulations-for-boats/','RYA gas safety regulations') + ', ' + a('https://www.boatsafetyscheme.org/requirements-examinations-and-certification/non-private-boat-standards/part-7-lpg-installations/cylinder-lockerhousing-drains/','Boat Safety Scheme on locker drains') + '; sprayhood prices from ' + a('https://forums.ybw.com/threads/how-much-would-you-expect-to-pay-for-a-sprayhood.618267/','YBW') + ' and ' + a('https://www.sabresails.co.uk/sprayhood-replacement','Sabre Sails') + ' (anecdotal).',
  'Teak and non-slip: ' + a('https://www.yachtingworld.com/features/teak-alternatives-decking-options-126023','Yachting World on teak alternatives') + ', ' + a('https://www.pbo.co.uk/expert-advice/how-to-replace-a-worn-teak-deck-95959','PBO on replacing a teak deck') + ', ' + a('https://forums.ybw.com/threads/new-teak-decks-costs.454470/','YBW on costs') + ' (anecdotal), ' + a('https://www.practical-sailor.com/boat-maintenance/repair-tools-materials/non-skid-ten-years-after/','Practical Sailor non-skid test') + ', ' + a('https://www.pbo.co.uk/expert-advice/how-to-apply-kiwigrip-to-your-deck-88409','PBO on KiwiGrip') + '.'
])}

  <h3>The reference fleet on deck</h3>
{compare('Steering and deck gear on the reference boats', ['', 'Steering', 'Winches (as found)', 'Anchor gear (as found)', 'Known deck weaknesses'], [
  ['Moody 33', 'wheel on a pedestal; Whitlock cable in conduit implied {TWO}; emergency tiller in the aft cabin {TWO}', 'Lewmar 40 primaries on one Mk II {TWO}', 'windlass and anchor from new {TBC}', 'coachroof windows {ONE}; chainplate cover plates {TWO}; stiff conduit steering {TWO}'],
  ['Sadler 32', 'tiller; some converted to wheels', 'Lewmar, sizes {TBC}', '11 kg CQR typical {TWO}; no windlass from new', 'chainplate leaks into the balsa side decks; small portlights leak {TWO}'],
  ['Bavaria 1060', 'wheel {TWO}; maker {TBC}', '{TBC}', '{TBC}', 'acrylic windows {ONE}; nothing else found'],
  ['Gib’Sea 31', 'tiller {TWO}', 'two halyard, two sheet winches, make {TBC}', '11 kg CQR and a 7 kg kedge, 15 m of chain, on one boat {TWO}', 'rudder bearings wear and give play {ONE}; pre-1982 mast-step frame rot reported by one listing site {TBC}'],
  ['Gib’Sea 33 (2002)', 'Whitlock wheel; rod or cable {TBC}', 'Lewmar 30ST primaries and a 16ST halyard winch; Goiot toe rail and deck gear {TWO}', 'electric windlass an option (Quick on one boat) {TWO}', 'none found'],
  ['Finnsailer 35', 'hydraulic, two wheels {TWO}', '{TBC}', 'electric windlass and CQR on individual boats {TWO}', 'teak decks and wheelhouse windows often assumed, not confirmed {TBC}'],
])}

  <h3 id="deck--checklist">The deck in one afternoon: a buyer’s checklist</h3>
  <ol>
    <li><strong>Steer it.</strong> Wheel from stop to stop with the boat still: play, notches, stiffness. Then open the locker and watch the quadrant while someone turns the wheel.</li>
    <li><strong>Find the emergency tiller</strong> and fit it. On a hydraulic boat, find the bypass valve.</li>
    <li><strong>Every wire, chain and sheave</strong> on a cable system: rag test, chain centred, stops meeting their supports. Ask how old the wire is.</li>
    <li><strong>Anchor gear.</strong> Read the anchor type and weight; check the chain against the gypsy stamp and count how much there is; look at the windlass terminals and the breaker.</li>
    <li><strong>Winches.</strong> Spin each drum: it should click one way and lock the other. Ask when they were last serviced.</li>
    <li><strong>Stanchions and cleats.</strong> Push and pull every one; look underneath for backing plates and stains.</li>
    <li><strong>Windows and hatches.</strong> Crazing, gaskets, stains on the lining below; hose the boat and sit inside.</li>
    <li><strong>Drains and lockers.</strong> Bucket down the cockpit drains and the gas-locker drain; seals on every locker lid.</li>
    <li><strong>Then the surveyor</strong>, who will moisture-meter the deck around every fitting you have just looked at.</li>
  </ol>

  <h3>Worth watching</h3>
{videos([
 ('ybsq_4RwBJA', 'How to service a winch', 'Yachting Monthly', 'A magazine-quality strip, clean and rebuild of a Lewmar-type winch, matching the steps in the winch card.'),
 ('rRsd6uhFWJM', 'Chain and cable steering maintenance, part 2', 'Ocean Navigator magazine, with Edson Marine', 'The maker of most cable systems walks the below-deck inspection: cables, quadrant and the sheaves under the pedestal.'),
 ('hsobS6LCGrk', 'Anchor test 99: sand seabed', 'SV Panope', 'Underwater footage of Mantus, Excel, Spade, Rocna and Fortress anchors setting in sand, from the most-cited independent test series.'),
 ('xQhoKHT1PW8', 'Steering sheave maintenance', 'Jacob E. Marine', 'Inspecting and lubricating the sheaves in a cable steering system.'),
 ('DMmlQ_ZeyNI', 'Steering failure at sea: use an emergency tiller', 'The Sailing Academy', 'Fitting and steering with an emergency tiller, which is the drill this section asks you to practise.'),
 ('jKHzvfO1UfY', 'Anchor test 124: CQR versus Delta', 'SV Panope', 'The two anchors actually found on the reference fleet, head to head on the seabed.'),
 ('A4m2EvjTZ5Y', 'Re-bedding deck bolts with butyl tape', 'Sail Life', 'Butyl bedding done on a real boat, including getting the old butyl off.'),
 ('Yh0Xn8WsG9w', 'Lewmar hatch lid replacement', 'Lewmar', 'The manufacturer’s own procedure for the hatches on many boats of this class.'),
])}

  <h3>Terms used in this section</h3>
  <h4 class="terms__group">Steering</h4>
{terms([
 ("tiller-arm","Tiller","A lever fixed to the head of the rudder stock. Push it one way and the boat turns the other."),
 ("tiller-extension","Tiller extension","A hinged rod on the end of a tiller so the helm can sit out on the side deck or reach a winch."),
 ("steer-wheel","Wheel","Turns the rudder through a mechanism: chain and cable, rod or hydraulics. Mounted on a pedestal."),
 ("pedestal","Pedestal","The hollow column in the cockpit that carries the wheel, usually the compass and often the engine controls; the steering chain runs down inside it."),
 ("chain-sprocket","Sprocket and chain","The toothed wheel on the wheel’s axle and the bicycle-type chain that runs over it, joining the wheel to the two steering cables."),
 ("steering-cable","Steering cables","The two wires, one from each end of the chain, that run to the two ends of the quadrant. Edson says replace them every five years."),
 ("steering-sheave","Sheaves","Pulleys that turn the steering cables round corners on their way aft. Scored sheaves mean a misaligned cable."),
 ("steering-quadrant","Quadrant","The fan-shaped fitting clamped to the top of the rudder stock that the cables pull on. A radial drive does the same job with a full wheel instead of a fan."),
 ("rudder-stops","Rudder stops","Blocks either side of the quadrant that limit the rudder’s swing before it hits the hull or the chain runs off the sprocket."),
 ("steer-stock","Rudder stock","The shaft the rudder blade turns on, rising through the hull to the quadrant and the emergency-tiller socket."),
 ("rudder-tube","Rudder tube","The tube moulded into the hull that the rudder stock passes through, with a bearing at the top and one at the bottom."),
 ("steer-bearings","Rudder bearings","The upper and lower bushes the stock turns in. Play here is felt as a knock at the helm."),
 ("steer-rudder","Rudder","The blade under the stern that steers the boat. The Hull section covers how it is hung."),
 ("emergency-tiller","Emergency tiller","A bar that fits a square socket on the stock head, under a deck plate, when the wheel system fails. Fit it in harbour before you need it at sea."),
 ("autopilot-drive","Autopilot drive","The motor or ram that moves the rudder for the autopilot: a tiller pilot on a tiller, a belt-driven wheel pilot, or a ram on the quadrant below deck."),
 ("bevel-box","Bevel gearbox","The right-angle gearbox at each end of a rod steering system, at the pedestal and at the rudder stock."),
 ("torque-tube","Torque tube","The rotating rod or tube that joins the gearboxes of a rod steering system."),
 ("helm-pump","Helm pump","The small hand pump behind a hydraulic steering wheel; turning the wheel pumps oil to the ram."),
 ("hydraulic-hose","Hydraulic hoses","The two hoses that carry oil between the helm pump and the ram. Air or a leak in them means a helm that turns without steering."),
 ("hydraulic-ram","Hydraulic ram","The cylinder whose piston pushes a tiller arm on the stock. Its end seals are where hydraulic systems leak."),
 ("hp-lock","Lock valves","Non-return valves in each hydraulic helm pump: they stop the rudder turning the wheel, and let two helms share one ram."),
 ("hp-autopilot","Hydraulic autopilot pump","An electric pump teed into the steering hoses; the autopilot steers through the same ram as the wheels."),
 ("bypass-valve","Bypass valve","A valve that joins the two sides of a hydraulic ram. Open, the wheels are disconnected so the emergency tiller can move the rudder; closed, the wheels and any hydraulic autopilot steer. Open by mistake, there is no steering."),
 ("weather-helm-deck","Weather helm","The boat’s tendency to turn into the wind, felt as a steady pull on the helm. A little is normal; hydraulic steering hides it."),
])}
  <h4 class="terms__group">Anchoring</h4>
{terms([
 ("anchor","Anchor","The hook. It holds by digging into the seabed, not by weight, and a modern design holds several times better than the one the boat was born with."),
 ("anchor-plough","Plough anchor","The CQR (with a hinged shank) and the one-piece Delta: the shape most boats of this age carry. Reliable, mediocre holding by modern standards."),
 ("anchor-claw","Claw anchor","The Bruce and its copies: sets easily, holds modestly, sits well on a bow roller."),
 ("anchor-newgen","Scoop (new-generation) anchor","Spade (1996), Rocna (2004), Mantus, Ultra and others: a concave fluke, often with a roll bar, that digs in at once and holds far more per kilogram."),
 ("anchor-danforth","Flat fluke anchor","Danforth and the aluminium Fortress: two flat flukes on a hinged stock. Superb in sand and mud, poor in weed and rock, folds flat; the usual kedge."),
 ("anchor-chain","Anchor chain","Calibrated galvanised chain, 8 or 10 mm on this class, made to a standard link size so it fits the gypsy. Its weight is the shock absorber."),
 ("windlass-unit","Windlass","A winch for chain, manual or electric. Its gypsy grips the links; the load must be taken off it by a stopper or a cleat once the anchor is down."),
 ("chain-stopper","Chain stopper","A hinged catch (a pawl) on the foredeck that drops onto a link and holds the chain, so the windlass is not left carrying the load."),
 ("navel-pipe","Navel pipe","The pipe or hole in the deck that the chain drops through into the locker; also called the spurling pipe."),
 ("chain-locker-deck","Chain locker","The compartment in the bow the chain falls into. It needs a drain and enough depth for the chain to pile up."),
 ("snubber","Snubber","A short, stretchy nylon rope from a hook on the chain to a cleat, taking the load off the windlass and stopping the chain snatching in a swell."),
 ("bow-roller-fitting","Bow roller","The fitting at the stem with a wheel the chain runs over and a cradle the anchor stows in. Needs a pin over the chain so it cannot jump out."),
 ("mooring-cleat","Mooring cleat","A horn cleat on the foredeck for mooring lines and the snubber; bolted through a backing plate because the loads are the highest on the deck."),
 ("deck-fairlead","Fairlead","A fitting that guides a rope over the deck edge without chafing it, and does not hold it."),
 ("scope-depth","Depth","For anchoring, the depth of water at high tide plus the height of the bow roller above the water: the number you multiply to get the chain to let out."),
 ("scope-ratio","Scope","The ratio of chain out to depth, counting the height of the bow. Commonly given as four or five to one in settled weather {TWO} and six or more in strong wind; more scope means a flatter pull and a better-set anchor. Yachting Monthly’s version: metres of chain equal to knots of wind plus metres of boat."),
 ("kedge","Kedge","A second, lighter anchor, often a flat fluke type, for holding the stern, a second line in a gale or pulling the boat off when it has run aground."),
 ("catenary","Catenary","The curve a chain hangs in between bow and anchor. Its weight keeps the pull on the anchor horizontal until the wind straightens it out."),
])}
  <h4 class="terms__group">Winches and deck gear</h4>
{terms([
 ("winch-drum","Winch drum","The barrel the rope is wound round, three or four turns. Its size number is roughly the pull in kilograms for one kilogram on the handle."),
 ("self-tailing-jaws","Self-tailing jaws","Two sprung discs on top of a winch that grip the rope’s tail, so one person can wind with both hands."),
 ("stripper-arm","Stripper arm","The finger on top of a self-tailing winch that peels the tail out of the jaws as the drum turns."),
 ("winch-handle-socket","Handle socket","The square hole in the top of the winch the handle fits into. Handles float away; carry a spare."),
 ("winch-gears","Winch gears","The gearing inside the base that multiplies the handle’s turns; two-speed winches change gear when you wind the other way."),
 ("pawls","Pawls","Small spring-loaded catches that let the drum turn one way and lock the other. Oil them, never grease them; replace the springs at every service."),
 ("winch-base","Winch base","The part bolted through the deck or coaming. Cracks and leaks start here."),
 ("clutch-body","Rope clutch","A lever-operated jaw on the coachroof that holds a loaded rope so the winch can be used for another line."),
 ("clutch-cam","Clutch cam","The toothed block inside a rope clutch that presses the rope onto the base to hold it."),
 ("clutch-lever","Clutch lever","Pushed down, it holds the rope; lifted, it releases it. Under heavy load, release only with the rope back on a winch."),
 ("clutch-rope","Line in a clutch","The halyard or reefing line held in the clutch. It chafes where it sits; move it a few centimetres now and then."),
 ("horn-cleat","Horn cleat","Two horns on a stem, for a figure-of-eight of rope. Length rule of thumb: 25 mm for every 1.5 mm of rope diameter."),
 ("cleat-backing","Cleat backing plate","A plate under the deck that spreads a cleat’s load across the laminate; without one the bolts pull through, which is where most cleat failures happen."),
 ("cleat-load","Mooring load","The pull on a cleat from a mooring line or snubber: sideways and upward together, tonnes when the boat jerks, so the bolts work in shear and tension at once."),
 ("cam-cleat","Cam cleat","Two spring-loaded toothed jaws that grip a rope pulled down between them and release with a flick upward; for sheets and control lines."),
 ("genoa-car-deck","Genoa car and track","The sliding block on the side-deck track that sets the genoa sheet angle; pin-stop cars move only when the sheet is slack, ball-bearing cars move under load."),
])}
  <h4 class="terms__group">Guardrails and keeping the water out</h4>
{terms([
 ("chafe","Chafe","Wear from a rope or sail rubbing on something, over and over. The commonest way ropes and sails die."),
 ("seize","Seize (two meanings)","A part that has seized is stuck solid with corrosion. To seize a shackle pin is to bind it shut with wire so it cannot unscrew. Same word, opposite ideas."),
 ("pontoon","Pontoon","A floating jetty in a marina that boats tie up alongside."),
 ("stanchion","Stanchion","A post along the deck edge, about 600 mm tall, carrying the guardrail wires."),
 ("stanchion-base","Stanchion base","The foot of a stanchion, bolted through the deck with a backing plate. Levered by every body that falls against the rail, so the commonest deck leak."),
 ("stanchion-leak","Stanchion base leak","Water past a levered, cracked base into the deck core: soft deck and stained lining below."),
 ("guardrail-wire","Guardrails (lifelines)","The two wires along each side from pulpit to pushpit; upper one at least 600 mm above the deck by the racing rules. Plastic-covered wire hides its own rust."),
 ("pelican-hook","Pelican hook","The hinged hook with a sliding keeper that closes a gate in the guardrails."),
 ("toe-rail-edge","Toe rail","The raised strip along the deck edge that stops feet and gear sliding off; slotted aluminium on many boats, and a place to clip a block."),
 ("jackstays-deck","Jackstays","Webbing straps along each side deck that a harness tether clips to. They weaken in sunlight; about five years in UK use, stowed below when not sailing."),
 ("df-fitting","Deck fitting","Anything bolted through the deck: cleats, stanchion bases, tracks, winches, the windlass. Each bolt is a path for water into the core unless the hole is sealed."),
 ("df-bolt","Through-bolt","A bolt passing right through the deck to a nut and backing plate below. Screws into the deck skin alone pull out."),
 ("sealant-bed","Sealant bed","The layer of sealant under a fitting, with a countersunk ring around each bolt that stays put when the fitting is tightened."),
 ("epoxy-annulus","Epoxy ring","The hole through a cored deck drilled oversize, filled with epoxy and redrilled, so the bolt passes through solid plastic and a leak cannot reach the core."),
 ("df-backing","Backing plate","A metal or plywood plate under the deck that spreads a fitting’s load over the laminate."),
 ("df-outer-skin","Outer skin","The top GRP layer of a sandwich deck, the one the fitting sits on."),
 ("df-core","Deck core","The balsa or plywood filling between the two skins of a sandwich deck. Dry it is stiff and light; wet it is mush."),
 ("df-inner-skin","Inner skin","The GRP layer on the cabin side of a sandwich deck."),
 ("butyl","Butyl tape","A sticky, non-hardening sealant tape for bedding fittings: stays flexible for decades, comes apart again, no cure time, but is not a glue."),
 ("polyurethane-sealant","Polyurethane sealant","Sikaflex 291 or 3M 5200: strong, near-permanent adhesive sealant. Use where you never want the joint apart, and not on acrylic (291 cracks it; 295 UV with primer is the glazing grade)."),
 ("framed-window","Framed window","A pane clamped between aluminium frames with a rubber gasket, the frame bedded to the cabin side. Leaks at the gasket and at the frame bolts as both age."),
 ("bonded-window","Bonded window","A thick acrylic pane glued to the outside of the cabin with a flexible adhesive and no frame. Fails when the pane crazes or the adhesive lets go."),
 ("crazing-acrylic","Crazing (acrylic)","A web of fine cracks in an acrylic pane or hatch lid from sun, stress and harsh cleaners. Hatch lids craze first because they face the sky."),
 ("houdini-hatch","Houdini hatch","A toughened-glass hatch in an aluminium frame, common on 1970s and 1980s British boats. A leak round the opening lid is cured with a new lid seal, which the maker sells; a leak between the glass and the frame cannot be resealed, the maker says, so that hatch is replaced whole."),
 ("gas-locker-deck","Gas locker","A sealed box for the gas cylinder that opens only from the top and drains overboard through a pipe of at least 19 mm bore, so leaking gas cannot reach the cabin."),
 ("cockpit-drains-deck","Cockpit drains","Pipes from the cockpit floor to skin fittings, sized by the ISO standard to empty a full cockpit by gravity within a time set by the boat’s design category; often crossed so the leeward one does not back-flood."),
 ("sprayhood-deck","Sprayhood","The folding canvas hood over the companionway, on a stainless frame. Owners replace the canvas and its windows roughly once a decade {TWO}."),
 ("teak-deck","Teak deck","Teak planks laid over the GRP deck, screwed and glued on older boats. Beautiful, and the most expensive thing on the boat to replace when the planks wear through."),
 ("non-slip","Non-slip","The textured surface of the deck: a moulded pattern in the GRP, a rolled-on textured paint, or glued sheet. Worn smooth, it is renewed with paint."),
])}

  <div class="planned">
    <p>Planned for this section</p>
    <ul>
      <li>Photographs of faults: a quadrant and cables, a corroded stanchion base, a crazed hatch, a dezincified skin fitting under a cockpit drain (still to be found under a CC licence)</li>
    </ul>
  </div>
</section>
'''
finish(page, ROOT + 'sections/05-deck.html', others=(ROOT + 'sections/03-hull.html', ROOT + 'sections/04-rig.html', ROOT + 'sections/02-fleet.html', ROOT + 'sections/00-start.html'))
