# Generates sections/12-seas.html for Sailing 101.
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_common import *
import gen_seas_diagrams as g
import gen_seas_maps as mp


page = f'''<section id="seas">
  <h2>Seas and cruising grounds</h2>
  <p class="lead">The same boat behaves like a different boat in different waters. A skipper who learned in the tideless Adriatic has to relearn passage timing in the English Channel; one who learned in the Channel has to learn to fear a clear sky over the Velebit mountains. This section is a first orientation for the six waters this site covers: the <a href="#seas--channel">English Channel</a>, the <a href="#seas--north-sea">North Sea</a>, the <a href="#seas--baltic">Baltic</a>, the <a href="#seas--med">Mediterranean</a>, the <a href="#seas--adriatic">Adriatic</a> and the <a href="#seas--black-sea">Black Sea</a>. It does not replace the pilot book for the area, which you should buy before you go.</p>

  <details class="first-words" open>
    <summary>Six words before anything else</summary>
    <dl>
      <dt>Pilot book</dt><dd>A guide to a coast for yachts: harbours, anchorages, dangers, local rules and weather. The first thing to buy for a new area.</dd>
      <dt>Fetch</dt><dd>The distance of open water the wind blows across. The longer the fetch, the bigger the waves.</dd>
      <dt>Tidal gate</dt><dd>A headland or channel that can be passed comfortably only at certain states of the tide (see <a href="#navigation">Navigation</a>).</dd>
      <dt>Overfalls</dt><dd>Rough, breaking water where a strong tidal stream runs over an uneven seabed or round a headland; a tide race.</dd>
      <dt>Fall wind</dt><dd>Cold air pouring down a mountainside onto the sea, like the bora: sudden and very gusty.</dd>
      <dt>Lead</dt><dd>In the skerries, a marked channel between the rocks.</dd>
    </dl>
  </details>
  <p class="conf-key"><b>Marks used below:</b> {ONE} single source; {TWO} sources disagree or anecdotal; {TBC} not yet verified. <b>How this section was checked:</b> in September 2026 the facts were checked by web search against the pages linked under “Sources and confidence”. The search results were read, but the pages themselves could not be opened from the editing session. Rules, fees and channels change: check them in a current pilot book or with the national authority before you go.</p>

  <h3>At a glance</h3>
{compare('Six cruising grounds compared', ['', 'Tide', 'Typical summer wind', 'Harbours and mooring', 'Season (guidance)', 'The thing to respect'], [
  ['English Channel', 'large: ranges of several metres, strong streams', 'westerlies from Atlantic depressions, and sea breezes', 'marinas with pontoons, drying harbours, moorings', 'May to September', 'the tidal streams at headlands, and shipping'],
  ['North Sea', 'moderate to large, with strong streams in the channels', 'westerlies, often fresh', 'marinas, drying harbours in the Wadden Sea', 'May to September', 'shallow banks, wind against tide, fog, shipping'],
  ['Baltic', 'almost none; the level moves with wind and pressure', 'light to moderate, variable', 'box berths (south), bow-to a rock (north), marinas', 'June to August at its best', 'rocks in the skerries, and cold water'],
  ['Mediterranean', 'small in most places', 'sea breezes, and strong named winds', 'stern-to with lazy lines, anchoring', 'April to October', 'the mistral and the meltemi'],
  ['Adriatic', 'small; spring tides can exceed a metre in the far north', 'the afternoon maestral', 'marinas and town quays stern-to, buoys in bays', 'May to October', 'the bora, which can arrive suddenly'],
  ['Black Sea', 'almost none', 'moderate; north-easterlies in autumn', 'fewer marinas; fishing and commercial harbours', 'June to September', 'drifting mines since 2022, short steep seas and sudden storms'],
], wide=True, stack=True)}

  <h3 id="seas--channel">English Channel</h3>
  <p>Some of the strongest tidal streams and the largest tidal ranges in Europe, around a busy shipping lane, on a coast of fine harbours a day’s sail apart. It is where much of northern Europe learns to sail, and it teaches tide.</p>
{figure('fig-map-channel', 'Channel map', mp.viewbox('channel'), 'The English Channel', 'A map of the English Channel from Cornwall and Brittany in the west to the Dover Strait in the east. Red dots mark tidal gates: the Lizard, Start Point, Portland Bill, St Alban’s Head, the Alderney Race and Barfleur. Cruising areas in italics: the West Country, the Solent, the Channel Islands and North Brittany. An amber triangle marks the Dover Strait traffic separation scheme. Harbours are named along both coasts.', mp.channel(), 'Plan a Channel passage round the tidal gates: arrive at each with the stream, or at slack water. Schematic, not for navigation; coastline from Natural Earth (public domain).', note=HINT, start=0.4)}
  <ul>
    <li><strong>Tide:</strong> the range varies a lot along the coast. On the English side it is smallest around Poole, Weymouth and Portland, about two metres at springs, and larger to the east, about 6 m at Dover, and to the west, nearly 5 m at Plymouth. The biggest ranges are on the French side: the Gulf of St Malo and the Channel Islands have among the largest tides in the world, well over 10 m at big spring tides at St Malo. A harbour you can enter at half tide may be a mudflat at low water.</li>
    <li><strong>Tidal gates:</strong> the streams run hardest round the headlands and through the gaps between the islands. Portland Bill, St Alban’s Head, Start Point, the Alderney Race (Raz Blanchard) and Cap de la Hague are the famous ones; the Alderney Race runs at up to about 9 knots at springs, and more at equinoctial tides. Pass them near slack water, or with the stream, and never with a strong wind against it. Overfalls (tide races) are marked on the chart with wavy symbols.</li>
    <li><strong>Shipping:</strong> the Dover Strait traffic separation scheme is one of the busiest in the world, watched by the coastguard’s Channel Navigation Information Service on radar and VHF. Cross it on a heading at right angles to the lanes, quickly, and keep a proper lookout; ferries cross the Channel at speed in every direction.</li>
    <li><strong>Weather:</strong> westerly depressions arrive off the Atlantic, some faster than forecast. The Solent and the big estuaries are sheltered; the open Channel is not, and a wind against the tide off a headland builds a dangerous sea.</li>
    <li><strong>Formalities:</strong> the UK is outside the EU and the Schengen area, so crossing to France, Belgium or the Netherlands and back needs customs and immigration formalities in both directions: arriving in the UK, an online pleasure craft report. See <a href="#licences">Licences and qualifications</a>.</li>
  </ul>
{figure('fig-wind-tide', 'wind against tide', '0 0 900 320', 'Wind with the tide and wind against the tide', 'Two side views of the sea with the same wind blowing from left to right. Left: the tidal stream runs the same way as the wind, and the waves are long and low. Right: the tidal stream runs against the wind, and the waves are short and steep, with breaking crests.', g.wind_tide(), 'The same force 5 can be a pleasant sail or a punishing one, depending on which way the tide is running. In the Channel and the North Sea, plan headlands and estuary bars for when the wind and the tide go the same way.', note=HINT)}

{photo('seas-cap-de-la-hague.jpg', 'A tall stone lighthouse on a rock offshore under a dark sky, with a low island on the horizon to the left', 'Cap de la Hague lighthouse, at the tip of the Cotentin, with Alderney on the horizon: the Alderney Race runs between them.', '@ S@ndrine', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0/', 'https://www.flickr.com/photos/133835212@N03/51492189792/', 1024, 576, 'https://www.flickr.com/photos/neelsandrine/')}
  <h3 id="seas--north-sea">North Sea</h3>
  <p>Shallow, tidal and busy, with long coasts of sand and few natural harbours in places. A tough school with good rewards: the Dutch and German islands, the Wadden Sea, and the way into the Baltic.</p>
{figure('fig-map-north-sea', 'North Sea map', mp.viewbox('north-sea'), 'The southern North Sea', 'A map of the southern North Sea from the Thames Estuary to Denmark. Cruising areas in italics: Zeeland, the IJsselmeer and the Wadden Sea behind the Frisian islands. A dashed line marks the Kiel Canal from Brunsbüttel on the Elbe to Kiel. Amber triangles mark the shifting banks off the Thames Estuary and the Belgian coast.', mp.north_sea(), 'The shallow southern North Sea, with the Kiel Canal as the short cut into the Baltic. Wind farms and platforms are not drawn: they are on the chart. Schematic, not for navigation; coastline from Natural Earth (public domain).', note=HINT, start=0.45)}
  <ul>
    <li><strong>Banks and channels:</strong> much of the southern North Sea is shallow, with sandbanks that shift. In the Wadden Sea, behind the Dutch, German and Danish islands, the channels between the banks are marked with buoys and withies (small branches on stakes) that are moved as the sand moves, and some harbours dry at low water: a place where bilge-keel, lifting-keel and flat-bottomed boats, which sit upright on the sand, are at home. A fin or long keel dries out only against a wall or with legs.</li>
    <li><strong>Sea state:</strong> a shallow sea builds steep waves quickly, and a strong onshore wind against an ebb tide at a harbour entrance can make it impassable. Do not approach a shallow entrance in a strong onshore wind.</li>
    <li><strong>Offshore:</strong> wind farms, oil and gas platforms, and traffic separation schemes off the Dutch and German coasts. Whether small craft may pass through a wind farm differs by country: UK wind farms are generally open, with small safety zones round each turbine; the Netherlands has opened a few; German and Belgian ones are closed to yachts. Fog is common in spring and early summer.</li>
    <li><strong>The Kiel Canal</strong> (Nord-Ostsee-Kanal) links the Elbe at Brunsbüttel with the Baltic at Kiel, saving the long way round Denmark. Yachts use it by day only and under engine, not sail alone (motor-sailing shows the cone), and must reach a pleasure-craft berth before dark. It has charged a small fee; from 2027 it is due to be free for pleasure craft.</li>
  </ul>

{photo('seas-wadden-harbour.jpg', 'Yachts and motor boats sitting upright on the mud at their pontoons in a small harbour at low tide', 'Low tide at Horumersiel on the German Wadden Sea coast: the boats sit on the mud at their berths until the tide returns.', 'Aagnverglaser', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', 'https://commons.wikimedia.org/wiki/File:Yachten_im_Hafen_Horumersiel_bei_Ebbe_(2).jpg', 1280, 960, 'https://commons.wikimedia.org/wiki/User:Aagnverglaser')}
  <h3 id="seas--baltic">Baltic</h3>
  <p>An almost tideless, brackish sea with two characters: the shallow, sandy south of Denmark and Germany, with small harbours everywhere, and the rocky skerry coasts of Sweden and Finland, with their thousands of islands and anchorages in the north.</p>
{figure('fig-map-baltic', 'Baltic map', mp.viewbox('baltic'), 'The Baltic', 'A map of the southern and central Baltic, from Kiel to the Gulf of Finland. Cruising areas in italics: the Danish South Sea, the Stockholm archipelago, Åland and the Archipelago Sea off Turku. Amber triangles mark reported GPS jamming near Kaliningrad and the Russian waters off Kaliningrad and at the head of the Gulf of Finland.', mp.baltic(), 'The Baltic’s two characters: the sandy, shallow south of Denmark and Germany, and the rocky skerry coasts of Sweden and Finland. Schematic, not for navigation; coastline from Natural Earth (public domain).', note=HINT, start=0.3)}
  <ul>
    <li><strong>Water:</strong> brackish, getting fresher to the north and east; less salt means less corrosion and, in the fresher north, less fouling, and a boat floats a little deeper. It is cold: even in high summer, a person in the water cools quickly.</li>
    <li><strong>Water level:</strong> no real tide, but the level rises and falls with the wind and air pressure, by tens of centimetres in ordinary weather and much more in a storm: in October 2023 the water at Flensburg rose 2.27 m above mean sea level. Check the local forecast of water level before entering a shallow harbour.</li>
    <li><strong>Skerries:</strong> in the Stockholm archipelago, the Åland Islands and the Finnish Archipelago Sea, you follow marked channels (leads) between rocks, many unmarked beyond them. Detailed charts, careful pilotage and the depth sounder are essential; keep to the lead unless you know the water.</li>
    <li><strong>Mooring:</strong> box berths between posts in Denmark and Germany (see <a href="#manoeuvres">Manoeuvres</a>); in Sweden and Finland, bow-to a rock with a stern anchor, or bow-to a pontoon with a stern buoy. For a stern buoy, come in slowly bow first, pass a line from the stern through the buoy’s ring as you pass it (a boathook helps), and pay it out as you go on to the pontoon; then take it tight to hold the bow off. Many local boats use a long buoy hook on the end of the line.</li>
    <li><strong>The right of public access</strong> in Sweden allows anchoring and going ashore almost anywhere outside private gardens and nature reserves, for a short stay (generally up to about a day), with respect for landowners and wildlife. Finland’s everyman’s right is similar but stricter about staying overnight near someone’s land {TWO}. Some bird and seal sanctuaries are closed to landing in the breeding season.</li>
    <li><strong>Season:</strong> short and bright: roughly June to August at its best, with very long days in the north. Many boats carry a diesel heater for the nights.</li>
    <li><strong>Harbour dues:</strong> a 2026 survey by YACHT magazine of 83 German Baltic harbours found guest berths costing 14 to 40 euros a night (for what length of boat, the survey does not say).</li>
    <li><strong>Military areas:</strong> several countries have naval firing and exercise areas marked on the charts, with warnings broadcast when they are active {TBC}. Stay out of Russian waters and any closed area.</li>
    <li><strong>GPS interference:</strong> jamming and spoofing of satellite positioning has been widely reported over parts of the Baltic since 2023, especially around Kaliningrad, with position errors of tens of metres and more. Keep a paper chart, the logbook and the traditional ways of fixing position (see <a href="#navigation">Navigation</a>) ready, and be suspicious of a plotter position that jumps.</li>
  </ul>
{figure('fig-skerry', 'bow-to a rock', '0 0 900 400', 'Mooring bow-to a rock in the Scandinavian way', 'Seen from above: a rocky shore with trees at the top. A boat lies bow-to the rock, held by two bow lines spread wide to pins in the rock, and held off by a stern anchor dropped well out astern. Labels: check the depth all the way in; crew step ashore from the bow.', g.skerry(), 'Choose a rock sheltered from the forecast wind, with deep water close to it; approach slowly, dropping the stern anchor as you go, and have the bow crew ready with the lines and a rock pin (bergkil) and hammer.')}

{photo('seas-skerry-harbour.jpg', 'A small yacht lying still in a sheltered pool between granite islands with pine trees, lines running ashore to the rocks', 'A natural harbour among the granite skerries of south-east Sweden, the boat held by lines ashore to the rock.', 'Henri Bergius', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0/', 'https://www.flickr.com/photos/15087210@N00/52079630737/', 1024, 768, 'https://www.flickr.com/photos/bergie/')}
  <h3 id="seas--med">Mediterranean</h3>
  <p>Warm water, long seasons, deep bays, and very small tides in most places. The weather is usually kind in summer, and when it is not, it has a name.</p>
{figure('fig-map-med', 'Mediterranean map', mp.viewbox('med'), 'The Mediterranean and its named winds', 'A map of the Mediterranean from Spain to Turkey. Blue arrows show the direction each named wind blows from: the mistral down the Rhône valley, the tramontane off the Pyrenees, the libeccio from the south-west towards Corsica, the sirocco from Africa, the gregale from the north-east near Malta, and the meltemi from the north through the Aegean. Cruising areas in italics: the Balearics, the Côte d’Azur, Corsica and Sardinia, the Ionian, the Cyclades and the Dodecanese.', mp.med(), 'The arrows show the typical direction of each wind, not its strength or how often it blows; see the list below. Schematic, not for navigation; coastline from Natural Earth (public domain).', note=HINT, start=0.35)}
  <ul>
    <li><strong>Tide:</strong> small in most places, a few tens of centimetres, with exceptions such as the Gulf of Gabès in Tunisia, about 2 m at springs, and the northern Adriatic. Streams are weak; currents are driven by the wind.</li>
    <li><strong>Winds</strong> (named, like all winds, for the direction they blow <em>from</em>): on settled days, sea breezes that build in the afternoon and die at night (see the drawing). Then the named winds:
      <ul>
        <li><strong>Mistral:</strong> a cold, dry north-westerly down the Rhône valley into the Gulf of Lion and towards Corsica and Sardinia, often under a clear sky, strong for days; most common in winter and spring. When one is forecast, stay in harbour or in a bay sheltered from the north-west; do not start a crossing of the Gulf of Lion.</li>
        <li><strong>Tramontane:</strong> a similar north-westerly off the Pyrenees, along the Catalan and Roussillon coasts.</li>
        <li><strong>Meltemi:</strong> the summer north wind of the Aegean, strongest in July and August and in the afternoon, often force 6 to 7 for days in the Cyclades, and sometimes 8, easing after sunset. Plan island hops for the mornings, before it builds; choose harbours and anchorages open to the south, and expect a rough passage going north.</li>
        <li><strong>Sirocco:</strong> a hot south or south-easterly from Africa, humid and hazy by the time it crosses the sea, sometimes carrying red dust.</li>
        <li><strong>Gregale:</strong> a strong north-easterly of the central Mediterranean, around Malta and the Ionian Sea, mostly in winter.</li>
        <li><strong>Libeccio, levante and poniente:</strong> the south-westerly of the Ligurian Sea and Corsica, and the easterly and westerly of the Strait of Gibraltar and the Alboran Sea.</li>
      </ul></li>
    <li><strong>Sea state:</strong> a short, steep sea for the wind, because the fetch is limited.</li>
    <li><strong>Mooring:</strong> stern-to with lazy lines or your own anchor (see <a href="#manoeuvres--med">Manoeuvres</a>); marinas are expensive in high season.</li>
    <li><strong>Anchoring:</strong> the water is often deep right up to the shore, so anchorages are chosen carefully. Seagrass (<em>Posidonia</em>) meadows are protected, and anchoring on them is banned in the Balearics for every boat and in parts of France for boats over 24 m, and restricted elsewhere: anchor in sand, which shows as pale patches.</li>
  </ul>
{figure('fig-sea-breeze', 'sea breeze', '0 0 900 330', 'The sea breeze by day and the land breeze by night', 'Two cross-sections of a coast. Day: the sun heats the land, warm air rises over it, and a sea breeze blows onshore at the surface, with a return flow aloft. Night: the land cools faster than the sea, and a lighter land breeze blows offshore.', g.sea_breeze(), 'The sea breeze is the everyday wind of Mediterranean and Adriatic summers, and of many northern coasts on sunny days: calm in the morning, a good sailing breeze by early afternoon, fading at dusk.')}

  <h3 id="seas--adriatic">Adriatic</h3>
  <p>Croatia’s coast has more than a thousand islands, most of them in long chains parallel to the shore, with sheltered channels between them: short hops, clear water and anchorages everywhere. Slovenia, the Italian coast, Montenegro and Albania complete the sea.</p>
{figure('fig-map-adriatic', 'Adriatic map', mp.viewbox('adriatic'), 'The Adriatic', 'A map of the Adriatic from Venice and Trieste to Bari and Montenegro. Blue arrows: the bora falling off the mountains at Trieste and, fiercest, under the Velebit at Senj; the maestral from the north-west on summer afternoons, along the Croatian coast; the jugo from the south-east. Cruising areas in italics: Istria, Kvarner, the Kornati, Central Dalmatia, Dubrovnik and the Bay of Kotor.', mp.adriatic(), 'The Croatian coast and its islands, where most Adriatic cruising happens, lie under the mountains that the bora falls from. Schematic, not for navigation; coastline from Natural Earth (public domain).', note=HINT, start=0.35)}
  <ul>
    <li><strong>Maestral:</strong> the summer afternoon north-westerly, a sea breeze of force 3 to 5, strongest in the early afternoon, the best sailing wind of the season {TWO}. It fails when a change in the weather is coming.</li>
    <li><strong>Jugo</strong> (sirocco): a warm, humid south-easterly that builds over a day or two, with cloud, rain and a long swell, strongest in the south and on open coasts. It gives warning.</li>
    <li><strong>Bora</strong> (bura): the dangerous one. A cold north-easterly that falls off the coastal mountains, often behind a cold front, sometimes out of a clear sky. Its gusts are violent close under the mountains, especially below the passes: near Trieste, Senj, along the Velebit channel and under the Biokovo mountains at Makarska, where gusts of 60 knots and more are not unusual. A cap of cloud on the mountain crests is the classic warning. When a bora is forecast, be in a harbour or an anchorage well sheltered from the north-east, with good holding, before it arrives, and stay there.</li>
    <li><strong>Formalities:</strong> Croatia requires a navigation permit (vignette) and a tourist tax for each person on board, arranged online or at the first port, plus a recognised skipper’s licence and a radio certificate for the skipper; the tourist tax is paid online through the eVisitor nautika portal. National parks such as Kornati, Krka and Mljet charge entry fees. See <a href="#licences">Licences and qualifications</a>.</li>
    <li><strong>Mooring:</strong> marinas, town quays stern-to with lazy lines, restaurant jetties (the owner expects you to eat there), and fee-paying mooring buoys in many bays.</li>
  </ul>
{figure('fig-bora', 'the bora', '0 0 900 370', 'How the bora falls off the mountains onto the sea', 'A cross-section with the sea on the left and coastal mountains and an inland plateau on the right. Cold, dense air piles up inland, pours over the crest under a cap of cloud, falls down the slope and accelerates, and hits the sea in violent gusts close under the mountains, tearing spray off the water. Further out the gusts ease.', g.bora(), 'A fall wind is strongest where the slopes are steepest and the passes funnel it, so the worst gusts are close to the mainland coast, not out at sea. Forecasts give warning of most boras, but a bora can still arrive suddenly, out of a clear sky; the local forecasts broadcast continuously on VHF by the harbour masters are the ones to listen to.')}
{photos(photo('seas-bora-senj.jpg', 'A dark, choppy sea streaked with spray, with islands and bare mountains on the far side', 'The sea churned by the bora near Senj, at the northern end of the Velebit, with the islands across the channel.', 'Perun at German Wikipedia', 'CC BY-SA 3.0', 'http://creativecommons.org/licenses/by-sa/3.0/', 'https://commons.wikimedia.org/wiki/File:Bura_vor_Senj,_vodena_prasina_(Wasserstaub).JPG', 1280, 960), photo('seas-bora-cloud.jpg', 'Seen from an aircraft: a bank of cloud lying on a mountain ridge, and below it a channel of sea streaked with long white lines, between the mainland and a bare island', 'The bora seen from an airliner at about 11,600 m, across the island of Pag near Novalja: its cloud sits on the Velebit mountains, and the gusts streak the sea in the channel below.', 'Marcel Vosswinkel', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', 'https://commons.wikimedia.org/wiki/File:Wind_Bora_near_Novalja_Croatia.jpg', 1280, 960))}

  <h3 id="seas--black-sea">Black Sea</h3>
  <p>A large, enclosed, almost tideless sea, about half as salty as the ocean, with a short season of settled weather and fewer yachting facilities than the Mediterranean. The Bulgarian and Romanian coasts are the usual cruising ground for EU boats; Turkey’s long northern coast is more remote.</p>
{figure('fig-map-black-sea', 'Black Sea map', mp.viewbox('black-sea'), 'The Black Sea', 'A map of the Black Sea. Harbours are named on the Bulgarian coast (Balchik, Varna, Nesebar, Burgas, Sozopol) and the Romanian coast (Constanța, Mangalia), with Istanbul and the Bosphorus to the south-west. Amber triangles warn of drifting mines reported in the western sea since 2022 and of the war zone off Ukraine. A blue arrow shows the autumn and winter north-easterlies.', mp.black_sea(), 'Keep to the western coasts, follow the navigational warnings for mines, and stay well clear of Ukrainian and Russian waters. Schematic, not for navigation; coastline from Natural Earth (public domain).', note=HINT, start=0.05)}
  <ul>
    <li><strong>Sea state:</strong> in a strong wind the sea builds a short, steep chop quickly, and storms can arrive fast outside the summer months. Autumn and winter bring hard north-easterlies.</li>
    <li><strong>Harbours:</strong> Bulgaria has marinas and harbours at Balchik, Varna, Nesebar, Burgas and Sozopol, among others; Romania at Constanța and Mangalia. Many are fishing or commercial harbours with a yacht corner; facilities are thinner than further west; Varna and Balchik are ports of entry.</li>
    <li><strong>Safety:</strong> since the war in Ukraine began in 2022, drifting sea mines have been reported in the western Black Sea, and a Turkish, Bulgarian and Romanian mine-clearance group has destroyed well over a hundred since 2024; parts of the sea are closed or dangerous. Read the current navigational warnings (NAVTEX and the national authorities) before every passage, and stay well clear of any restricted area.</li>
    <li><strong>Formalities:</strong> Bulgaria and Romania are in the EU, and joined the Schengen area for sea and air borders in March 2024 and fully in January 2025; Turkey is not, and a yacht entering Turkey needs a transit log, now issued electronically, at the first port of entry. See <a href="#licences">Licences and qualifications</a>.</li>
  </ul>
{sources('seas', [
  'Channel and North Sea: ' + a('https://assets.publishing.service.gov.uk/media/5a79ff7f40f0b66eab998ff5/SEA8_TechRep_Hydrography.pdf','UK Government SEA 8 hydrography report') + ', ' + a('https://en.wikipedia.org/wiki/Alderney_Race','Wikipedia, Alderney Race') + ', ' + a('https://gov.uk/government/publications/dover-strait-crossings-channel-navigation-information-service/dover-strait-crossings-channel-navigation-information-service-cnis','GOV.UK, Dover Strait crossings and CNIS') + ', ' + a('https://www.rya.org.uk/boating-abroad/entry-and-exit-formalities/','RYA, entry and exit formalities') + ', ' + a('https://www.gov.uk/government/publications/import-and-export-pleasure-craft-on-non-eu-voyages-leaving-or-arriving-in-uk-c1331','GOV.UK, pleasure craft reports') + '; drying out: ' + a('https://www.pbo.co.uk/seamanship/drying-out-how-to-safely-take-the-ground-103761','Practical Boat Owner, drying out') + '; wind farms: ' + a('https://www.yacht.de/en/travel-and-charter/the-netherlands/offshore-wind-farms-sailors-watch-out-these-navigation-rules-apply-in-the-north-sea-and-baltic-sea/','YACHT, wind farm rules') + ', ' + a('https://www.yachtingmonthly.com/sailing-skills/navigating-wind-farms-the-dos-and-the-donts-72009','Yachting Monthly, wind farms') + '; Kiel Canal: ' + a('https://www.gdws.wsv.bund.de/SharedDocs/Downloads/DE/NOK_Befahrungsabgaben/Flyer/PDF_Merkbl_Spobo_eng.pdf?__blob=publicationFile&v=12','German waterways authority, guidance for recreational craft') + ', ' + a('https://www.yacht.de/en/travel-and-charter/germany/the-kiel-canal-free-of-charge-for-pleasure-craft-from-2027/','YACHT, free from 2027') + '.',
  'Baltic: ' + a('https://www.uni-kiel.de/en/university/details/news/181-ostsee-sturmflut','Kiel University, the 2023 storm surge') + ', ' + a('https://visitsweden.com/what-to-do/nature-outdoors/nature/sustainable-and-rural-tourism/the-right-of-public-access/','Visit Sweden, right of public access') + ', ' + a('https://itameri.fi/en/leisure/leisure-time-at-the-sea/everymans-rights-and-obligations/','Itämeri.fi, everyone’s rights at sea') + ' ², ' + a('https://www.yacht.de/en/sailing-knowledge/manoeuvre/mooring-at-the-skerry-how-to-carry-out-the-manoeuvre-in-sweden-s-natural-harbours/','YACHT, mooring at a skerry') + ', ' + a('https://www.yachtingworld.com/expert-sailing-techniques/how-to-berth-and-anchor-a-yacht-in-the-baltic-149774','Yachting World, berthing in the Baltic') + ', ' + a('https://spire.com/blog/space-reconnaissance/gnss-interference-report-russia/','Spire, GNSS interference over the Baltic') + ', ' + a('https://www.yacht.de/en/travel-and-charter/germany/baltic-sea-harbours-2026-sailors-can-still-find-free-berths-here/','YACHT, Baltic harbours 2026') + '. Military areas: still TBC.',
  'Mediterranean: ' + a('https://os.copernicus.org/articles/20/1051/2024/','Ocean Science, Mediterranean tides') + ', ' + a('https://en.wikipedia.org/wiki/Gulf_of_Gab%C3%A8s','Wikipedia, Gulf of Gabès') + ', ' + a('https://en.wikipedia.org/wiki/Mistral_(wind)','Wikipedia, mistral') + ', ' + a('https://sailingissues.com/meltemi.html','Sailing Issues, the meltemi') + ', ' + a('https://www.britannica.com/science/gregale','Britannica, gregale') + ', ' + a('https://www.icomia.org/posidonia-oceanica-yacht-moorings/','ICOMIA, Posidonia and moorings') + ', ' + a('https://www.pya.org/knowledge-base/french-anchorage-regulations','PYA, French anchoring rules') + '.',
  'Adriatic: ' + a('https://en.wikipedia.org/wiki/Bora_(wind)','Wikipedia, bora') + ', ' + a('https://www.sea-help.eu/en/adriatic-sea-news/wind-weather-adriatic-croatia-bora/','SeaHelp, Adriatic winds') + ', ' + a('https://goxperience-sailing.com/maestral-croatias-summer-sailing-wind/','the maestral') + ' ² (sources give force 3 to 5), ' + a('https://www.sea-help.eu/en/guide/croatia-permit-tourist-tax-lighthouse-fee/','SeaHelp, Croatian permit and tourist tax') + ', ' + a('https://www.nautika.evisitor.hr/faq/','eVisitor nautika, tourist tax') + ', ' + a('https://www.croatia-yachting-charter.com/en/blog/boat-licenses-croatia','Croatia Yachting, licences') + ', ' + a('https://www.croatia-catamaran.com/en/important-sailing-information/weather-and-winds-in-croatia','VHF weather channels') + '.',
  'Black Sea: ' + a('https://www.noonsite.com/place/bulgaria/','Noonsite, Bulgaria') + ', ' + a('https://www.navalnews.com/naval-news/2024/07/turkiye-bulgaria-and-romania-activate-mcm-black-sea-task-group/','Naval News, the mine-countermeasures group') + ', ' + a('https://home-affairs.ec.europa.eu/news/bulgaria-and-romania-join-the-schengen-area-2025-01-03_en','European Commission, Bulgaria and Romania join Schengen') + ', ' + a('https://www.gocekonline.com/en/blue-cruise-guide/sailing-and-navigation/transitlog-turkey-yachts','the Turkish e-Transitlog') + '.',
  'Maps: coastlines from ' + a('https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-land/','Natural Earth, 1:10m land') + ' (public domain), simplified; places, gates, winds and areas placed by us from their latitude and longitude, as a schematic only.',
  'Checked by web search, September 2026; the pages could not be opened directly. Rules and fees change: check before you go.',
])}

  <h3 id="seas--water">Water temperature and toilet waste</h3>
  <p>Two things that differ from sea to sea and that a crew notices at once: how cold the water is, which decides how long a person in it stays useful (see <a href="#sailing--mob">Man overboard</a>), and whether the toilet may be pumped straight into the sea. Many countries now require a holding tank, a tank that keeps the toilet waste on board until it is pumped out ashore at a pump-out station; check the rules of each country before you go, and on an older boat check that it has a tank and a deck fitting to empty it.</p>
{compare('Water temperature and holding-tank rules by sea', ['Sea', 'Sea temperature in August', 'Toilet waste and holding tanks'], [
  ['English Channel', 'about 16 °C in mid-Channel, warmer towards both shores', 'UK: no legal requirement for a pleasure boat at sea, though discharge is banned on inland waterways, and a tank is needed on some waterways joined to the sea, such as the Caledonian Canal. France: a boat with a toilet built from 2008 needs a holding tank or a treatment system to use ports, moorings and anchorages; an older boat must not discharge in ports or designated anchorages'],
  ['North Sea', '12 to 17 °C on average in summer', 'Netherlands: no toilet water may be discharged on inland waters, which include the Wadden Sea, and on coastal waters too&nbsp;². Germany: see the Baltic. Belgium: no tank rule known'],
  ['Baltic', 'about 20 °C in the south, cooler in the north', 'The Baltic states’ Helsinki Convention (HELCOM) extends its sewage rules, holding tanks included, to pleasure craft, but they are not yet law in every Baltic country. Sweden: no toilet waste may be discharged at all, foreign boats included, since 2015. Finland: no untreated sewage within 12 miles of land. Denmark: a tank on boats built from 2000, and on larger boats built from 1980. Germany: a tank on German boats built from 2003, and on older ones over 11.5 m'],
  ['Mediterranean', '{TBC}: no typical figure found from an official source', 'France: as for the Channel. Spain: no untreated sewage within 12 miles. Greece: a tank is a practical necessity, though not known to be a legal requirement. Italy: no discharge in harbours, marinas, at moorings or bathing zones under local harbour-master ordinances, and elsewhere only beyond 3 miles at 4 knots or more for small boats (see Boat systems) ¹. Turkey: see the Black Sea'],
  ['Adriatic', 'about 24 to 27 °C, with little difference between north and south ¹', 'Croatia: no toilet waste may be discharged into the sea from a boat under 15 m; it must be kept on board, and older boats with direct-discharge toilets had to fit a tank by the end of 2021. Whether this binds foreign boats is not stated {TBC}'],
  ['Black Sea', 'about 23 to 28 °C ¹', 'Turkey: any discharge may be treated as illegal. Pump-outs are logged on the Blue Card (Mavi Kart), which from 11 August 2026 is digital for every yacht, whatever its flag ¹. Bulgaria: no wastewater discharge within 12 miles except into shore facilities ¹. Romania: no untreated wastewater from any vessel ² (see Boat systems)'],
], wide=True, stack=True)}
{sources('water temperature and toilet waste', [
  'Sea temperature: ' + a('https://assets.publishing.service.gov.uk/media/5a79ff7f40f0b66eab998ff5/SEA8_TechRep_Hydrography.pdf','UK Government SEA 8 report') + ' (Channel), ' + a('https://www.bsh.de/EN/TOPICS/Monitoring_systems/State_of_the_North_Sea/state_of_the_north_sea_node.html','BSH, state of the North Sea') + ', ' + a('https://www.smhi.se/kunskapsbanken/oceanografi/haven-runt-sverige/temperatur-i-havet','SMHI, temperature in the sea') + ' (Baltic), ' + a('http://jadran.gfz.hr/temperatura.html','University of Zagreb, Adriatic temperature') + ', ' + a('https://seatemperature.info/august/','seatemperature.info, August averages') + ' ¹ (Adriatic, Aegean and Black Sea ranges). Figures are long-term averages; a marine heatwave can add several degrees.',
  'Toilet waste: ' + a('https://thegreenblue.org.uk/you-and-your-boat/info-and-advice/water-pollution-prevention/blackwater-disposal-and-pump-out-locations/','The Green Blue, blackwater') + ' (UK), ' + a('https://www.rya.org.uk/boating-abroad/holding-tanks/','RYA, holding tanks') + ' (Denmark, Germany, Finland, Belgium, France, Spain, Greece, Turkey), ' + a('https://helcom.fi/about-us/convention/annexes-to-the-convention-2/annex-iv/','HELCOM, Annex IV') + ', ' + a('https://www.transportstyrelsen.se/sv/sjofart/fritidsbatar/batliv-miljo/avfall-fran-fritidsbat/toalettavfall/','Transportstyrelsen, toilet waste') + ', ' + a('https://iplo.nl/thema/water/afvalwater-activiteiten/scheepvaart/pleziervaart/','IPLO, pleasure craft') + ' (the Dutch coastal-waters ban is from the RYA only), ' + a('https://narodne-novine.nn.hr/clanci/sluzbeni/2020_01_13_223.html','Croatia, regulation on boats and yachts (NN 13/2020)') + ', ' + a('https://ytb.org.tr/haberler/agustos-2026--da-mavi-kart-sistemi-degisiyor-yat-ve-teknelerde-dijital-atik-takibi-basliyor_79','YTB, the digital Blue Card') + '.',
  'Official pages opened and read in September 2026 where marked as such above; the RYA page is a summary, not the law. Rules change: check before you go.',
])}

  <h3 id="seas--berths">What a visitor’s night costs</h3>
  <p>One night for a 10 m monohull in high season, from each harbour’s own published tariff: real prices from one place each, not averages. Where the tariff charges by area, we took a 10 × 3.4 m boat; tourist taxes, water and electricity are extra unless the notes say otherwise.</p>
{compare('A visitor’s night for a 10&nbsp;m yacht in high season, from current tariffs (2026 unless noted; last known where marked); VAT included unless the notes say otherwise', ['Sea', 'Harbour', 'A night', 'Notes'], [
  ['English Channel', 'Port Chantereyne, Cherbourg (France)', '€41.10', 'VAT, water, electricity and tourist tax included; 1 May to 30 September'],
  ['English Channel', 'Weymouth Harbour (UK)', '£41 (about&nbsp;€48)', '1 April to 30 September; VAT not stated'],
  ['English Channel', 'Cowes Harbour, Trinity Landing (Solent, UK)', '£32.90 (about&nbsp;€38)', 'VAT and harbour dues included'],
  ['English Channel', 'Lymington Yacht Haven (Solent, UK)', '£56 (about&nbsp;€65)', 'summer'],
  ['North Sea', 'Marina Seaport IJmuiden (Netherlands)', '€34.08', '€13 plus €0.62 a square metre; no seasonal rates'],
  ['North Sea', 'KMJC, Scheveningen (Netherlands)', '€23.70', '€2.37 a metre, VAT included; tourist tax extra, per person'],
  ['North Sea', 'LCF, Cuxhaven (Germany)', '€15', 'yachts from April to October'],
  ['North Sea', 'Mercator Marina, Ostend (Belgium)', '€38.30 to €39.10 <span class=lk>last known</span>', '€3.83 a metre on the English and French pages, €3.91 on the Dutch one ²; probably a 2019 tariff'],
  ['North Sea', 'RYCO, Ostend (Belgium)', '€25 <span class=lk>last known</span>', 'July and August, from the club’s 2024 tariff'],
  ['Baltic', 'Sporthafen Kiel (Germany)', '€20', 'VAT included; summer season'],
  ['Baltic', 'Wasahamnen, Stockholm (Sweden)', 'SEK 400 (about&nbsp;€35)', '15 May to 15 September; no year printed on the price page ²'],
  ['Baltic', 'MarinaBay, Helsinki (Finland)', '€55', 'VAT, electricity and water included; season not stated'],
  ['Baltic (Kattegat)', 'Skagen (Denmark)', 'DKK 300 (about&nbsp;€40)', 'peak rate, 6 to 26 July; at the entrance to the Baltic'],
  ['Mediterranean', 'Calvi, Corsica (France)', '€43.30 before VAT (about&nbsp;€52 with it)', 'July and August; the tariff prints no VAT rate, we took France’s 20%'],
  ['Mediterranean', 'Club Nàutic Estartit (Spain)', '€75 to €85', 'by the boat’s beam; July and August'],
  ['Adriatic', 'ACI Marina Split (Croatia)', '€138 (€151.80 Friday to Sunday)', 'VAT, water and electricity included; 1 July to 31 August'],
  ['Adriatic', 'ACI Marina Umag (Croatia)', '€78', 'same terms; 1 July to 31 August'],
  ['Adriatic', 'Town harbours of Šibenik county (Croatia)', '€40', '€4 a metre, all year; water and electricity extra'],
  ['Aegean', 'Monemvasia town quay (Greece)', 'about €4', 'stern-to; alongside costs 25% more; the national rate of €150 a metre a year, divided by 365 (a 2025 tariff, still current); over 10.00 m the next band, about €4.70; water and electricity extra'],
  ['Aegean', 'Teos Marina (Turkey)', 'TRY 4,838 (about&nbsp;€87)', 'charged on at least 40 m², with VAT and stamp duty'],
  ['Black Sea', 'Port of Varna (Bulgaria)', '€10 before VAT', 'boats up to 10 m; tariff for July to December 2026'],
  ['Black Sea', 'Port Burgas (Bulgaria)', '€35 before VAT (about €42 with it), at least', 'a negotiated minimum of €3.50 a metre; yachts are priced case by case (2026 tariff)'],
  ['Black Sea', 'Marina Sozopol (Bulgaria)', '€27.50 <span class=lk>last known</span>', 'the price page is undated (seen September 2026); VAT not stated'],
  ['Black Sea', 'Tomis Marina, Constanța (Romania)', 'about €12 before VAT <span class=lk>last known</span>', 'length × beam × €0.35 a day, from a 2018 price sheet'],
], wide=True, stack=True)}
  <p>No authority defines a cruising season, but the tariffs show where each harbour draws its high season: July and August in Croatia, Corsica and Catalonia, with June and September a step lower; May to September at Cherbourg; mid-May to mid-September in Stockholm. The <em>season</em> column in the table at the top of this page is our guidance, drawn from these.</p>
{'  <p><strong>Check today’s price</strong> before you go, especially where the table says “last known”: ' + a('https://www.portchantereyne.fr/','Cherbourg') + ', ' + a('https://www.weymouth-harbour.co.uk/visiting/','Weymouth') + ', ' + a('https://app.cowes.co.uk/on-the-water/harbour-information/visitor-berthing/','Cowes') + ', ' + a('https://www.yachthavens.com/lymington-yacht-haven/berthing/berthing-rates','Lymington Yacht Haven') + ', ' + a('https://www.lymingtonharbour.co.uk/visitor-dues','Lymington Harbour') + ' and ' + a('https://www.yarmouth-harbour.co.uk/visitor-berths/visitor-mooring-charges/','Yarmouth') + ' (both nearby, not in the table), ' + a('https://www.mercatormarina.be/','Mercator Ostend') + ', ' + a('https://www.ryco.be/site/tarieven.html','RYCO') + ', ' + a('https://vynieuwpoort.be/en/visitors/','Nieuwpoort') + ' (nearby), ' + a('https://aci-marinas.com/','ACI marinas') + ', ' + a('https://port-varna.bg/en/Clients/Services','Port of Varna') + ', ' + a('https://port-burgas.bg/uslugi-i-ceni','Port Burgas') + ', ' + a('https://marinasozopol.com/en/prices','Marina Sozopol') + ', ' + a('https://www.marinadinevi.bg/en/full-book-berth/','Marina Dinevi') + ' and ' + a('http://www.port-balchik.com/bg/prices/','Balchik') + ' (nearby, no published price); the other harbours’ pages are in the sources below.</p>'}
{sources('visitor berths', [
  a('https://www.portchantereyne.fr/fileadmin/user_upload/Port_Chantereyne/Services_et_demarches/Informations_pratiques/Tarifs/Tarifs_visiteurs_2026_.pdf','Port Chantereyne, visitor tariffs 2026') + ' (PDF), ' + a('https://www.weymouth-harbour.co.uk/visiting/','Weymouth Harbour, visiting') + ', ' + a('https://www.marinaseaport.nl/en/prices/short-term-prices/','Marina Seaport IJmuiden') + ', ' + a('https://kmjc-site.e-captain.nl/jachthaven','KMJC Scheveningen') + ', ' + a('https://www.lcf-cuxhaven.de/gast.htm','LCF Cuxhaven') + ', ' + a('https://sporthafen-kiel.de/preise/gastliegeplaetze','Sporthafen Kiel, visitors') + ', ' + a('https://wasahamnen.se/prices/?lang=en','Wasahamnen') + ', ' + a('https://skagenlystbaadehavn.frederikshavn.dk/priser/priser-for-lystbaade','Skagen') + ', ' + a('https://en.marinabay.fi/hinnasto','MarinaBay Helsinki') + ', ' + a('https://calvi-marina.corsica/wp-content/uploads/2026/06/Tarifs-2026.pdf','Calvi, tariffs 2026') + ' (PDF), ' + a('https://cnestartit.com/wp-content/uploads/2025/12/Tarifes-Port-2026.pdf','Club Nàutic Estartit, 2026') + ' (PDF), ' + a('https://aci-marinas.com/wp-content/uploads/2023/04/ACI_Marinas_Prices.pdf','ACI price list, valid from 1 April 2026') + ' (PDF), ' + a('https://luskz.hr/pristojbe/','Šibenik-Knin county port authority') + ', ' + a('https://www.dltmonemvasias.gr/en/port-fund/prices/','Monemvasia port fund') + ', ' + a('https://teosmarina.com.tr/fiyatlar.html','Teos Marina, 2026 prices') + '.',
  a('https://www.cowes.co.uk/wp-content/uploads/2026/01/2026-Schedule-of-Charges.pdf','Cowes Harbour Commission, 2026 charges') + ' (PDF), ' + a('https://www.yachthavens.com/lymington-yacht-haven/berthing/berthing-rates','Lymington Yacht Haven') + ', ' + a('https://www.mercatormarina.be/en/rates-2019','Mercator Marina') + ' and ' + a('https://www.mercatormarina.be/nl/tarieven','its Dutch page') + ', ' + a('https://www.ryco.be/site/files/Tarieven.doc','RYCO 2024 tariff') + ', ' + a('https://port-varna.bg/content/10/files/PORT_VARNA_Tariff_Eng_2026_01.07-31.12.26_2.pdf','Port of Varna tariff, July to December 2026') + ' (PDF), ' + a('https://port-burgas.bg/uploads/HEADOFFICE/Terms%20&%20Prices%20of%20Services%20%E2%80%93%20Port%20Burgas%20EAD%20260514.pdf','Port Burgas, 2026') + ' (PDF), ' + a('https://marinasozopol.com/en/prices','Marina Sozopol') + ', ' + a('http://yo3kxl.netxpert.ro/diverse/barci/tarife_marine/marina_Tomis/Tarife%20marina_Tomis_2018.pdf','Tomis Marina, 2018 sheet') + ' (PDF, a copy).',
  'Each tariff opened and read in September 2026; euro figures at the ECB rates of 28 September 2026. “Last known” marks a price from an undated page or an older tariff, the newest that could be found. Prices change every year: check before you go.',
])}

  <h3 id="seas--forecasts">Where to get the forecast</h3>
  <p>Every coastal country has a national weather service with marine forecasts, and most broadcast them on VHF: usually announced first on channel 16, where the announcement names the working channel, then read on that channel, which depends on which aerial is nearest. The second table gives the broadcasts as published in September 2026. The channels and times change (Greece moved several channels in May 2026), so check them in the almanac or pilot book for the area, and note whether the times are UTC or local.</p>
{compare('National weather services with marine forecasts', ['Country', 'Service', 'Notes'], [
  ['United Kingdom', a('https://www.metoffice.gov.uk/', 'Met Office'), 'shipping forecast and inshore waters forecast; coastguard broadcasts on VHF'],
  ['France', a('https://meteofrance.com/', 'Météo-France'), 'coastal forecasts; broadcasts by the French coastguard (CROSS) on VHF'],
  ['Netherlands, Germany', a('https://www.knmi.nl/', 'KNMI') + ', ' + a('https://www.dwd.de/', 'DWD'), 'North Sea and Baltic forecasts'],
  ['Denmark, Sweden, Finland', a('https://www.dmi.dk/', 'DMI') + ', ' + a('https://www.smhi.se/', 'SMHI') + ', ' + a('https://www.fmi.fi/', 'FMI'), 'Baltic forecasts, including water levels'],
  ['Croatia', a('https://meteo.hr/', 'DHMZ'), 'Adriatic forecasts in Croatian, English, Italian and German'],
  ['Italy, Greece', a('https://www.meteoam.it/', 'Aeronautica Militare') + ', ' + a('https://www.emy.gr/', 'HNMS'), 'Mediterranean and Aegean forecasts'],
  ['Bulgaria, Romania, Turkey', a('https://www.meteo.bg/', 'NIMH') + ', ' + a('https://www.meteoromania.ro/', 'ANM') + ', ' + a('https://www.mgm.gov.tr/', 'MGM'), 'Black Sea forecasts'],
], stack=True)}
{compare('Weather on VHF, by country: as published in September 2026', ['Country', 'Station', 'Channels', 'Times', 'Language'], [
  ['United Kingdom', 'HM Coastguard', 'announced on 16, then 62, 63 or 64 (each aerial has its own)', 'a full broadcast twice a day and a shorter one every 3 hours, local time; the times differ by coastguard centre (Solent: 0730 and 1930)', 'English'],
  ['France: Channel and Atlantic', 'CROSS Gris-Nez, Jobourg, Corsen, Étel', 'announced on 16, then mostly 79 or 80', 'three times a day, at times that differ by aerial, French legal time; near-gale and stronger warnings every hour', 'French; Jobourg traffic bulletins and Jersey Radio (channel 82) in English'],
  ['France: Mediterranean', 'CROSS La Garde and Corsica', 'announced on 16, then 63, 64, 79 or 80', 'three times a day; sources disagree on the times ²', 'French; warnings in French and English. Monaco Radio, 23 and 24: a continuous loop'],
  ['Netherlands', 'Kustwacht (coastguard)', 'announced on 16, then 23 or 83', '0805, 1305, 1905 and 2305, Dutch local time', 'Dutch and English'],
  ['Germany', 'DP07 Seefunk (DWD forecasts)', 'announced on the working channel, not 16: for example Kiel 23, Elbe-Weser 83', '0945, 1245 and 1645 German local time, and 0745 and 1945 from May to August; only from Good Friday to 3 October', 'German'],
  ['Denmark', 'Lyngby Radio', 'announced on 16', 'no routine VHF forecast: warnings when issued, forecasts on request', 'Danish and English'],
  ['Sweden', 'Stockholm Radio', 'announced on 16, then the nearest station’s channel', 'coastal weather for small craft from 11 May to 31 August, twice a day, local time, at times that depend on the area (Utklippan to Hallands Väderö: 0915 and 1715)', 'Swedish'],
  ['Finland', 'Turku Radio', 'working channels shown on Fintraffic’s map', '0633 and 1833 UTC', 'navigational warnings in English; weather {TBC}'],
  ['Croatia', 'Rijeka, Split and Dubrovnik Radio', 'announced on 16, then the nearest aerial’s channel', 'four times a day, for example Split 0545, 1245, 1945 and 0045 (UTC or local not stated {TBC}). The harbour masters also run a continuous forecast loop, reported on 67, 69 and 73 ²', 'Croatian and English (the loop reportedly in four languages ²)'],
  ['Italy', 'Coastguard stations', 'announced on 16; a continuous loop is reported on 68 ²', '{TBC}: sources disagree', 'Italian; storm warnings in English too'],
  ['Greece', 'Olympia Radio', 'announced on 16, then a channel that differs by aerial', '0600, 1000, 1600 and 2200 UTC', 'Greek and English'],
  ['Turkey', 'Coastal Safety radio', '67', '0700 and 1900 UTC', 'Turkish and English'],
  ['Bulgaria', 'Varna Radio', 'announced on 16 and by DSC, then 26', '0733, 1333 and 1933 (UTC or local not stated {TBC})', 'Bulgarian and English'],
  ['Romania', 'Constanța Radio', '25', '0703, 1303 and 1903 UTC ¹', '{TBC}'],
], wide=True, stack=True)}
{sources('forecasts on VHF', [
  a('https://www.gov.uk/government/publications/advice-note-1033-maritime-safety-information-msi-leaflet/advice-note-1033-maritime-safety-information-msi-leaflet','MCA, maritime safety information leaflet') + ', ' + a('https://meteofrance.fr/sites/meteofrance.fr/files/files/editorial/Guide%20MARINE%202025.pdf','Météo-France, Guide marine 2025') + ' (PDF), ' + a('https://www.dirm.mediterranee.developpement-durable.gouv.fr/diffusion-de-la-meteo-et-des-avis-urgents-aux-a2695.html','DIRM Méditerranée') + ', ' + a('https://kustwacht.nl/pleziervaart/reisvoorbereiding/','Kustwacht') + ', ' + a('https://www.bsh.de/DE/PUBLIKATIONEN/_Anlagen/Downloads/Nautik_und_Schifffahrt/Sonstige-nautische-Publikationen/Wetter-und-Warnfunk.pdf?__blob=publicationFile&v=8','BSH, Wetter- und Warnfunk') + ' (PDF; Germany and Denmark), ' + a('https://stockholmradio.se/kustvader/','Stockholm Radio, coastal weather') + ', ' + a('https://www.fintraffic.fi/en/maritime_traffic/maritime-traffic-services/maritime-safety-radio','Fintraffic, maritime safety radio') + ', ' + a('https://www.plovput.hr/en/radio-service/maritime-safety-information-msi','Plovput, maritime safety information') + ', ' + a('https://www.itu.int/mmsapp/coastnote/download?adm=I&cga=I','ITU coast station notes, Italy') + ', ' + a('https://www.cosmote.gr/pdf/Business/Olympia_Radio_GMDSS_Broadcasts.pdf','Cosmote, Olympia Radio') + ' (PDF) and ' + a('https://hnhs.gr/en/631-2026-vhf-olympia-radio-transmission-frequency-change/','the May 2026 channel changes') + ', ' + a('https://www.mgm.gov.tr/eng/marine-broadcasts-shipping.aspx','MGM, marine broadcasts') + ', ' + a('https://www.vtmis.bg/en/structure/varna-radio/services','Varna Radio') + ', ' + a('https://euronaval.ro/statia-romana-de-coasta-constanta-radio-yqi/','Euronaval, Constanța Radio') + ' ¹.',
  'Official pages opened and read in September 2026, except the Croatian harbour-master loop and the Italian channel 68 (search results only, and they disagree) and Romania (a non-official page). The times are those the stations publish; check the current almanac before relying on them.',
])}

  <h3>Worth watching</h3>
{videos([
 ('OJhLSPBU-l0', 'Transiting the Kiel Canal: key points and rules', 'Sailing on a Dream', 'What a yacht needs to know before the locks at Brunsbüttel or Kiel.'),
 ('FualbbnIvlA', 'Baltic sailing #9: anchoring and mooring to the rocks in Scandinavian archipelagos', 'Sailing Around The Baltic Sea', 'Bow to the rock with a stern anchor, the Swedish and Finnish way.'),
 ('coKLoQRhY7M', 'Sailing the Dutch Wadden Sea', 'Perle III', 'Tides, channels and waves in the Wadden Sea, from a cruising yacht.'),
 ('qoDUSZSWDDc', 'How to approach and lock in at the Kiel Canal, Germany', 'Sailors & Seadogs', 'The approach and the lock itself.'),
 ('VZkoOBQKks8', 'Mooring to the rocks in the Swedish archipelago, easy like this', 'Mike Peuker', 'The same rock mooring, with a title in German and English.'),
 ('EBxqJ7H6lQQ', 'Bora winds then peaceful bays: sailing life in Croatia', 'Travel Sketch', 'A cruising yacht moving to shelter when a bora is forecast.'),
 ('gTrf-s1DEyg', 'No sails: sailing in bora (bura), 50+ knots wind, Croatia', 'AAAYacht0', 'What a strong bora looks like from a yacht, and why the forecast matters.'),
])}

  <h3>Terms used in this section</h3>
  <h4 class="terms__group">Wind and tide</h4>
{terms([
 ("wt-wind","Wind","The same wind in both drawings: it is the tide that changes the sea."),
 ("wt-tide-with","Wind with tide","The tidal stream running the same way as the wind: the waves lengthen and flatten."),
 ("wt-tide-against","Wind against tide","The tidal stream running against the wind: the waves shorten, steepen and break. Worst off headlands and at bars."),
 ("wt-long","Long, low waves","The sea with wind and tide together."),
 ("wt-steep","Short, steep waves","The sea with wind against tide: uncomfortable, slow and, in a strong wind, dangerous."),
 ("sb-rising","Rising warm air","Air heated over sunny land rises, drawing in cooler air from the sea."),
 ("sb-sea-breeze","Sea breeze","A daytime onshore wind caused by the land heating up; it starts late in the morning and fades at dusk."),
 ("sb-land-breeze","Land breeze","A lighter night-time offshore wind, as the land cools below the sea’s temperature."),
])}
  <h4 class="terms__group">The bora</h4>
{terms([
 ("bo-cold-air","Cold air inland","Cold, dense air that collects over the land behind the coastal mountains, often after a cold front."),
 ("bo-cap-cloud","Cap cloud","A bank of cloud sitting on the mountain crest as the bora pours over it: the classic warning sign."),
 ("bo-fall","Fall wind","Air falling down a mountain slope and speeding up; the bora is one, the mistral partly one."),
 ("bo-gusts","Bora gusts","Violent, short gusts close under the mountains and below passes, strong enough to lay a yacht flat."),
 ("bo-sea","Further offshore","The gusts ease away from the coast, but a strong bora can still blow hard far out."),
])}
  <h4 class="terms__group">On the maps</h4>
{terms([
 ("map-gate","Tidal gate","A headland or channel where the tidal stream runs hard, so a passage is timed to pass it with the stream or at slack water; a tidal race is the rough water there."),
 ("map-area","Cruising area","A stretch of coast with many harbours and anchorages close together, where most cruising yachts spend their time."),
 ("map-wind","Named wind","A local wind with a name, drawn blowing from where it comes from; each is described in the text."),
 ("map-caution","Caution","An area with a particular danger or restriction: shipping lanes, shifting banks, mines, GPS jamming or closed waters."),
 ("map-port","Harbour","A harbour or town named for orientation; the maps are schematic and show no approaches, depths or dangers."),
])}
  <h4 class="terms__group">The skerries</h4>
{terms([
 ("sk-bow-lines","Bow lines to the rock","Two lines from the bow to rock pins, rings or trees, spread wide to stop the bow swinging."),
 ("sk-step","Stepping ashore","From the bow onto the rock, often with a folding bow ladder; the rock may be slippery."),
 ("sk-stern-anchor","Stern anchor","A kedge anchor dropped astern on the approach, often on a reel of webbing tape at the pushpit, that holds the boat off the rock."),
 ("sk-depth","Depth close in","Skerry shores are often steep-to, but rocks can lie just under the surface close to them; watch the sounder and look into the water."),
])}

  <div class="planned">
    <p>Planned for this section</p>
    <ul>
      <li>A photo of the Alderney Race in full flow (still to be found under a CC licence)</li>
    </ul>
  </div>
</section>
'''
finish(page, ROOT + 'sections/12-seas.html', others=(ROOT + 'sections/03-hull.html', ROOT + 'sections/04-rig.html', ROOT + 'sections/05-deck.html', ROOT + 'sections/06-engine.html', ROOT + 'sections/07-systems.html', ROOT + 'sections/08-electronics.html', ROOT + 'sections/09-sailing.html', ROOT + 'sections/10-manoeuvres.html', ROOT + 'sections/11-navigation.html', ROOT + 'sections/02-fleet.html', ROOT + 'sections/00-start.html'))
