# Builds tools/coast_data.py, the land outlines for the Seas maps, from Natural Earth's 1:10m land polygons
# (public domain, naturalearthdata.com). Run once, or when a map's extent changes:
#   python3 tools/make_coast.py path/to/ne_10m_land.geojson
# The geojson is not kept in the repository; the generated coast_data.py is. Standard library only.
import json, math, os, sys

# name: (west, south, east, north) in degrees; the map is 900 units wide, its height follows the extent
MAPS = {
    'channel': (-6.2, 48.3, 2.6, 51.6),
    'north-sea': (-1.0, 50.7, 10.6, 55.8),
    'baltic': (9.0, 53.6, 30.5, 61.2),
    'med': (-1.5, 34.8, 28.8, 45.3),
    'adriatic': (12.2, 40.6, 20.0, 45.9),
    'black-sea': (26.2, 40.6, 42.0, 47.2),
}
W = 900

def projector(w, s, e, n):
    lat0 = math.radians((s + n) / 2)
    k = W / ((e - w) * math.cos(lat0))
    H = round((n - s) * k)
    return (lambda lon, lat: ((lon - w) * math.cos(lat0) * k, (n - lat) * k)), H

def clip(poly, H):
    """Sutherland-Hodgman against the rectangle 0..W, 0..H."""
    def inside(p, edge):
        x, y = p
        return {'l': x >= 0, 'r': x <= W, 't': y >= 0, 'b': y <= H}[edge]
    def cut(p, q, edge):
        (x1, y1), (x2, y2) = p, q
        if edge in 'lr':
            xe = 0 if edge == 'l' else W
            t = (xe - x1) / (x2 - x1)
            return (xe, y1 + t * (y2 - y1))
        ye = 0 if edge == 't' else H
        t = (ye - y1) / (y2 - y1)
        return (x1 + t * (x2 - x1), ye)
    out = poly
    for edge in 'lrtb':
        inp, out = out, []
        if not inp: break
        prev = inp[-1]
        for cur in inp:
            if inside(cur, edge):
                if not inside(prev, edge): out.append(cut(prev, cur, edge))
                out.append(cur)
            elif inside(prev, edge):
                out.append(cut(prev, cur, edge))
            prev = cur
    return out

def simplify(pts, eps):
    """Douglas-Peucker, iterative."""
    if len(pts) < 4: return pts
    keep = [False] * len(pts); keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        (x1, y1), (x2, y2) = pts[a], pts[b]
        dx, dy = x2 - x1, y2 - y1
        L = math.hypot(dx, dy) or 1e-9
        best, bi = 0, None
        for i in range(a + 1, b):
            d = abs(dy * (pts[i][0] - x1) - dx * (pts[i][1] - y1)) / L
            if d > best: best, bi = d, i
        if bi is not None and best > eps:
            keep[bi] = True
            stack += [(a, bi), (bi, b)]
    return [p for p, k in zip(pts, keep) if k]

def rings(geom):
    polys = geom['coordinates'] if geom['type'] == 'MultiPolygon' else [geom['coordinates']]
    for poly in polys:
        for ring in poly:
            yield ring

def build(path):
    data = json.load(open(path))
    all_rings = [r for f in data['features'] for r in rings(f['geometry'])]
    out = {}
    for name, (w, s, e, n) in MAPS.items():
        P, H = projector(w, s, e, n)
        parts = []
        for ring in all_rings:
            lons = [p[0] for p in ring]; lats = [p[1] for p in ring]
            if max(lons) < w - 1 or min(lons) > e + 1 or max(lats) < s - 1 or min(lats) > n + 1: continue
            pts = clip([P(lon, lat) for lon, lat in ring], H)
            if len(pts) < 3: continue
            xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
            if max(xs) - min(xs) < 2.5 and max(ys) - min(ys) < 2.5: continue
            # a closed ring: split it at the point farthest from the first, simplify each half
            far = max(range(len(pts)), key=lambda i: (pts[i][0] - pts[0][0]) ** 2 + (pts[i][1] - pts[0][1]) ** 2)
            pts = simplify(pts[:far + 1], 0.7)[:-1] + simplify(pts[far:] + [pts[0]], 0.7)[:-1]
            if len(pts) < 3: continue
            parts.append('M' + ' '.join(f'{x:.0f},{y:.0f}' for x, y in pts) + 'Z')
        out[name] = {'extent': (w, s, e, n), 'height': H, 'land': ''.join(parts)}
        print(name, H, len(parts), 'rings,', len(out[name]['land']) // 1024, 'KB')
    dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'coast_data.py')
    with open(dst, 'w') as f:
        f.write('# Generated by make_coast.py from Natural Earth 1:10m land (public domain). Do not edit by hand.\n')
        f.write('MAPS = ' + json.dumps(out, indent=0) + '\n')
    print('wrote', dst)

if __name__ == '__main__':
    build(sys.argv[1])
